from itertools import permutations
a = input('Enter letters: ')
b = tuple(a)
bb = []
bb1 = []
bb2 = []
bb3 = []
##print(b)
####print(len(b))

c = ['aa','ab','ad','ae','ag','ah','ai','al','am','an','ar','as','at','aw','ax','ay','ba','be','bi','bo','by','da','de','do','dy','ed','ef','eh','el','em','en','er',
     'es','et','ex','fa','fe','ga','gi','go','ha','he','hi','hm','ho','id','if','in','is','it','ja','jo','ju','ka','ki','la','li','lo','ma','me','mi','mo','mu','my',
     'na','ne','no','nu','od','oe','of','oh','oi','ok','om','on','op','or','os','ou','ow','ox','oy','pa','pe','pi','po','qi','re','sh','se','si','so','ta','te','ti',
     'to','uh','um','un','up','us','ut','wa','wo','we','wu','xi','xu','ya','ye','yi','yo','yu','za']

c1 = ['aah','aal','aas','aba','abb','abo','aby','ace','ach','act','add','ado','ads','adz','aff','aft','aga','age','ago','ags','aha','ahi','ahs','aia','aid','ail',
      'aim','ain','air','ais','ait','aka','ake','ala','alb','ale','alf','all','alp','als','alt','alu','ama','ame','ami','amp','amu','ana','and','ane','ani','ann',
      'ans','ant','any','ape','apo','app','apt','arb','arc','ard','are','arf','ark','arm','ars','art','ary','ash','ask','asp','ass','ate','ats','att','aua','aue',
      'auf','auk','ava','ave','avo','awa','awe','awk','awl','awn','axe','aye','ays','ayu','azo','baa','bac','bad','bag','bah', 'bal', 'bam', 'ban', 'bap', 'bar',
      'bas', 'bat', 'bay', 'bed', 'bee', 'beg', 'bel', 'ben', 'bes', 'bet', 'bey', 'bez', 'bib', 'bid','big', 'bin', 'bio', 'bis', 'bit', 'biz', 'boa', 'bob', 'bod',
      'bog', 'boh', 'boi', 'bok', 'bon', 'boo', 'bop', 'bor', 'bos', 'bot', 'bow', 'box', 'boy', 'bra', 'bro', 'brr', 'bru', 'bub', 'bud', 'bug', 'bum', 'bun', 'bur',
      'bus', 'but', 'buy', 'bye', 'bys', 'caa', 'cab', 'cad', 'cag', 'cam', 'can', 'cap', 'car', 'cat', 'caw', 'cay', 'caz', 'cee', 'cel', 'cep', 'cha', 'che', 'chi',
      'cid', 'cig', 'cis', 'cit', 'cly', 'cob', 'cod', 'cog', 'col', 'con', 'coo', 'cop', 'cor', 'cos', 'cot', 'cow', 'cox', 'coy', 'coz', 'cru', 'cry', 'cub', 'cud',
      'cue', 'cum', 'cup', 'cur', 'cut', 'cuz', 'cwm', 'dab', 'dad', 'dae', 'dag', 'dah', 'dak', 'dal', 'dam', 'dan', 'dap', 'das', 'daw', 'day', 'deb', 'dee', 'def',
      'deg', 'dei', 'del', 'den', 'dev', 'dew', 'dex', 'dey', 'dib', 'did', 'die', 'dif', 'dig', 'dim', 'din', 'dip', 'dis', 'dit', 'div', 'dob', 'doc', 'dod', 'doe',
      'dof', 'dog', 'doh', 'dol', 'dom', 'don', 'doo', 'dop', 'dor', 'dos', 'dot', 'dow', 'doy', 'dry', 'dso', 'dub', 'dud', 'due', 'dug', 'duh', 'dui', 'dun', 'dup',
      'duo', 'dux', 'dye', 'dzo', 'ean', 'ear', 'eas', 'eat', 'eau', 'ebb', 'ech', 'eco', 'ecu', 'edh', 'eds', 'eek', 'eel', 'een', 'eff', 'efs', 'eft', 'egg', 'ego',
      'ehs', 'eik', 'eke', 'eld', 'elf', 'elk', 'ell', 'elm', 'els', 'elt', 'eme', 'emo', 'ems', 'emu', 'end', 'ene', 'eng', 'ens', 'eon', 'era', 'ere', 'erf', 'erg',
      'erk', 'erm', 'ern', 'err', 'ers', 'ess', 'est', 'eta', 'eth', 'euk', 'eve', 'evo', 'ewe', 'ewk', 'ewt', 'exo', 'eye', 'faa', 'fab', 'fad', 'fae', 'fag', 'fah',
      'fan', 'fap', 'far', 'faw', 'fax', 'fay', 'fed', 'fee', 'feg', 'feh', 'fem', 'fen', 'fer', 'fes', 'fet', 'feu', 'few', 'fey', 'fez', 'fib', 'fid', 'fie', 'fig',
      'fil', 'fin', 'fir', 'fit', 'fix', 'fiz', 'flu', 'fob', 'foe', 'fog', 'foh', 'fon', 'fop', 'for', 'fou', 'fox', 'foy', 'fra', 'fro', 'fry', 'fub', 'fud', 'fug',
      'fum', 'fun', 'fur', 'gab', 'gad', 'gae', 'gag', 'gak', 'gal', 'gam', 'gan', 'gap', 'gar', 'gas', 'gat', 'gau', 'gaw', 'gay', 'ged', 'gee', 'gel', 'gem', 'gen',
      'geo', 'ger', 'get', 'gey', 'ghi', 'gib', 'gid', 'gie', 'gif', 'gig', 'gin', 'gio', 'gip', 'git', 'gju', 'gnu', 'goa', 'gob', 'god', 'goe', 'gon', 'goo', 'gor',
      'gos', 'got', 'gov', 'gox', 'goy', 'gub', 'gue', 'gul', 'gum', 'gun', 'gup', 'gur', 'gus', 'gut', 'guv', 'guy', 'gym', 'gyp', 'had', 'hae', 'hag', 'hah', 'haj',
      'ham', 'han', 'hao', 'hap', 'has', 'hat', 'haw', 'hay', 'heh', 'hem', 'hen', 'hep', 'her', 'hes', 'het', 'hew', 'hex', 'hey', 'hic', 'hid', 'hie', 'him', 'hin',
      'hip', 'his', 'hit', 'hmm', 'hoa', 'hob', 'hoc', 'hod', 'hoe', 'hog', 'hoh', 'hoi', 'hom', 'hon', 'hoo', 'hos', 'hot', 'how', 'hox', 'hoy', 'hub', 'hue', 'hug',
      'huh', 'hui', 'hum', 'hun', 'hup', 'hut', 'hye', 'hyp', 'ice', 'ich', 'ick', 'icy', 'ide', 'ids', 'iff', 'ifs', 'igg', 'ilk', 'ill', 'imp', 'ing', 'ink', 'inn',
      'ins', 'ion', 'ios', 'ire', 'irk', 'ish', 'ism', 'iso', 'ita', 'its', 'ivy', 'iwi', 'jab', 'jag', 'jai', 'jak', 'jam', 'jap', 'jar', 'jaw', 'jay', 'jee', 'jet',
      'jeu', 'jew', 'jib', 'jig', 'jin', 'jiz', 'job', 'joe', 'jog', 'jol', 'jor', 'jot', 'jow', 'joy', 'jud', 'jug', 'jun', 'jus', 'jut', 'kab', 'kae', 'kaf', 'kai',
      'kak', 'kam', 'kas', 'kat', 'kaw', 'kay', 'kea', 'keb', 'ked', 'kef', 'keg', 'ken', 'kep', 'ket', 'kex', 'key', 'khi', 'kid', 'kif', 'kin', 'kip', 'kir', 'kis',
      'kit', 'koa', 'kob', 'koi', 'kon', 'kop', 'kor', 'kos', 'kow', 'kue', 'kye', 'kyu', 'lab', 'lac', 'lad', 'lag', 'lah', 'lam', 'lap', 'lar', 'las', 'lat', 'lav',
      'law', 'lax', 'lay', 'lea', 'led', 'lee', 'leg', 'lei', 'lek', 'lep', 'les', 'let', 'leu', 'lev', 'lew', 'lex', 'ley', 'lez', 'lib', 'lid', 'lie', 'lig', 'lin',
      'lip', 'lis', 'lit', 'lob', 'lod', 'log', 'loo', 'lop', 'lor', 'los', 'lot', 'lou', 'low', 'lox', 'loy', 'lud', 'lug', 'lum', 'lur', 'luv', 'lux', 'luz', 'lye',
      'lym', 'maa', 'mac', 'mad', 'mae', 'mag', 'mak', 'mal', 'mam', 'man', 'map', 'mar', 'mas', 'mat', 'maw', 'max', 'may', 'med', 'mee', 'meg', 'meh', 'mel', 'mem',
      'men', 'mes', 'met', 'meu', 'mew', 'mho', 'mib', 'mic', 'mid', 'mig', 'mil', 'mim', 'mir', 'mis', 'mix', 'miz', 'mna', 'moa', 'mob', 'moc', 'mod', 'moe', 'mog',
      'moi', 'mol', 'mom', 'mon', 'moo', 'mop', 'mor', 'mos', 'mot', 'mou', 'mow', 'moy', 'moz', 'mud', 'mug', 'mum', 'mun', 'mus', 'mut', 'mux', 'myc', 'nab', 'nae',
      'nag', 'nah', 'nam', 'nan', 'nap', 'nas', 'nat', 'naw', 'nay', 'neb', 'ned', 'nee', 'nef', 'neg', 'nek', 'nep', 'net', 'new', 'nib', 'nid', 'nie', 'nil', 'nim',
      'nip', 'nis', 'nit', 'nix', 'nob', 'nod', 'nog', 'noh', 'nom', 'non', 'noo', 'nor', 'nos', 'not', 'now', 'nox', 'noy', 'nth', 'nub', 'nun', 'nur', 'nus', 'nut',
      'nye', 'nys', 'oaf', 'oak', 'oar', 'oat', 'oba', 'obe', 'obi', 'obo', 'obs', 'oca', 'och', 'oda', 'odd', 'ode', 'ods', 'oes', 'off', 'oft', 'ohm', 'oho', 'ohs',
      'oik', 'oil', 'ois', 'oka', 'oke', 'old', 'ole', 'olm', 'oms', 'one', 'ono', 'ons', 'ony', 'oof', 'ooh', 'ooh', 'oom', 'oon', 'oop', 'oos', 'oot', 'ope', 'ops',
      'opt', 'ora', 'orb', 'orc', 'ord', 'ore', 'orf', 'ors', 'ort', 'ose', 'oud', 'ouk', 'oup', 'our', 'ous', 'out', 'ova', 'owe', 'owl', 'own', 'owt', 'oxo', 'oxy',
      'oye', 'oys', 'pac', 'pad', 'pah', 'pal', 'pam', 'pan', 'pap', 'par', 'pas', 'pat', 'pav', 'paw', 'pax', 'pay', 'pea', 'pec', 'ped', 'pee', 'peg', 'peh', 'pel',
      'pen', 'pep', 'per', 'pes', 'pet', 'pew', 'phi', 'pho', 'pht', 'pia', 'pic', 'pie', 'pig', 'pin', 'pip', 'pir', 'pis', 'pit', 'piu', 'pix', 'plu', 'ply', 'poa',
      'pod', 'poh', 'poi', 'pol', 'pom', 'poo', 'pop', 'pos', 'pot', 'pow', 'pox', 'poz', 'pre', 'pro', 'pry', 'psi', 'pst', 'pub', 'pud', 'pug', 'puh', 'pul', 'pun',
      'pup', 'pur', 'pus', 'put', 'puy', 'pya', 'pye', 'pyx', 'qat', 'qin', 'qis', 'qua', 'rad', 'rag', 'rah', 'rai', 'raj', 'ram', 'ran', 'rap', 'ras', 'rat', 'rav',
      'raw', 'rax', 'ray', 'reb', 'rec', 'red', 'ree', 'ref', 'reg', 'reh', 'rei', 'rem', 'ren', 'reo', 'rep', 'res', 'ret', 'rev', 'rew', 'rex', 'rez', 'rho', 'rhy',
      'ria', 'rib', 'rid', 'rif', 'rig', 'rim', 'rin', 'rip', 'rit', 'riz', 'rob', 'roc', 'rod', 'roe', 'rok', 'rom', 'roo', 'rot', 'row', 'rub', 'ruc', 'rud', 'rue',
      'rug', 'rum', 'run', 'rut', 'rya', 'rye', 'sab', 'sac', 'sad', 'sae', 'sag', 'sai', 'sal', 'sam', 'san', 'sap', 'sar', 'sat', 'sau', 'sav', 'saw', 'sax', 'say',
      'saz', 'sea', 'sec', 'sed', 'see', 'seg', 'sei', 'sel', 'sen', 'ser', 'sew', 'sex', 'sey', 'sez', 'sha', 'she', 'shh', 'shy', 'sib', 'sic', 'sif', 'sik', 'sim',
      'sin', 'sip', 'sir', 'sis', 'sit', 'six', 'ska', 'ski', 'sky', 'sly', 'sma', 'sny', 'sob', 'soc', 'sod', 'sog', 'soh', 'sol', 'som', 'son', 'sop', 'sos', 'sot',
      'sou', 'sov', 'sow', 'sox', 'soy', 'soz', 'spa', 'spy', 'sri', 'sty', 'sub', 'sud', 'sue', 'sug', 'sui', 'suk', 'sum', 'sun', 'sup', 'suq', 'sur', 'sus', 'swy',
      'sye', 'syn', 'tab', 'tad', 'tae', 'tag', 'tai', 'taj', 'tak', 'tam', 'tan', 'tao', 'tap', 'tar', 'tas', 'tat', 'tau', 'tav', 'taw', 'tax', 'tay', 'tea', 'tec',
      'ted', 'tee', 'tef', 'tel', 'ten', 'tes', 'tet', 'tew', 'tex', 'the', 'tho', 'thy', 'tic', 'tid', 'tie', 'tig', 'tik', 'til', 'tin', 'tip', 'tis', 'tit', 'tix',
      'toc', 'tod', 'toe', 'tog', 'tom', 'ton', 'too', 'top', 'tor', 'tot', 'tow', 'toy', 'try', 'tsk', 'tub', 'tui', 'tum', 'tun', 'tup', 'tut', 'tux', 'twa', 'two',
      'twp', 'tye', 'tyg', 'udo', 'uds', 'uey', 'ufo', 'ugh', 'ugs', 'uke', 'ule', 'ulu', 'umm', 'ump', 'ums', 'umu', 'uni', 'uns', 'upo', 'ups', 'urb', 'urd', 'ure',
      'urn', 'urp', 'use', 'uta', 'ute', 'uts', 'utu', 'uva', 'vac', 'vae', 'vag', 'van', 'var', 'vas', 'vat', 'vau', 'vav', 'vaw', 'vee', 'veg', 'vet', 'vex', 'via',
      'vid', 'vie', 'vig', 'vim', 'vin', 'vis', 'vly', 'voe', 'vol', 'vor', 'vow', 'vox', 'vug', 'vum', 'wab', 'wad', 'wae', 'wag', 'wai', 'wan', 'wap', 'war', 'was',
      'wat', 'waw', 'wax', 'way', 'web', 'wed', 'wee', 'wem', 'wen', 'wet', 'wex', 'wey', 'wha', 'who', 'why', 'wig', 'win', 'wis', 'wit', 'wiz', 'woe', 'wof', 'wog',
      'wok', 'won', 'woo', 'wop', 'wos', 'wot', 'wow', 'wox', 'wry', 'wud', 'wus', 'wye', 'wyn', 'xis', 'yad', 'yae', 'yag', 'yah', 'yak', 'yam', 'yap', 'yar', 'yaw',
      'yay', 'yea', 'yeh', 'yen', 'yep', 'yes', 'yet', 'yew', 'yex', 'ygo', 'yid', 'yin', 'yip', 'yob', 'yod', 'yok', 'yom', 'yon', 'you', 'yow', 'yug', 'yuk', 'yum',
      'yup', 'yus', 'zag', 'zap', 'zas', 'zax', 'zea', 'zed', 'zee', 'zek', 'zel', 'zep', 'zex', 'zho', 'zig', 'zin', 'zip', 'zit', 'ziz', 'zoa', 'zol', 'zoo', 'zos',
      'zuz', 'zzz']

c2 = ['aahs', 'aals', 'abas', 'abba', 'abbe', 'abed', 'abet', 'able', 'ably', 'abos', 'abri', 'abut', 'abye', 'abys', 'aced', 'ache', 'achy', 'acid', 'acme', 'acne',
      'acre', 'acta', 'acts', 'acyl', 'adds', 'adit', 'ados', 'adze', 'aeon', 'aero', 'aery', 'afar', 'afro', 'agar', 'agas', 'aged', 'agee', 'ager', 'ages', 'agha',
      'agin', 'agio', 'agly', 'agma', 'agog', 'agon', 'ague', 'ahed', 'ahem', 'ahis', 'ahoy', 'aide', 'aids', 'ails', 'aims', 'ains', 'airn', 'airs', 'airt', 'airy',
      'aits', 'ajar', 'ajee', 'akee', 'akin', 'alae', 'alan', 'alar', 'alas', 'alba', 'albs', 'alec', 'alee', 'alef', 'ales', 'alfa', 'alga', 'alif', 'alit', 'alky',
      'alls', 'ally', 'alma', 'alme', 'alms', 'aloe', 'alow', 'alps', 'also', 'alto', 'alts', 'alum', 'amah', 'amas', 'ambo', 'amen', 'amia', 'amid', 'amie','amin',
      'amir', 'amis', 'ammo', 'amok', 'amps', 'amus', 'amyl', 'anas', 'ands', 'anes', 'anew', 'anga', 'anil', 'anis', 'ankh', 'anna', 'anoa', 'anon', 'ansa', 'anta',
      'ante', 'anti', 'ants', 'aped', 'aper', 'apes', 'apod', 'apos', 'apps', 'apse', 'aqua', 'arak', 'arbs', 'arch', 'arco', 'arcs', 'area', 'ares', 'arfs', 'aria',
      'arid', 'aril', 'arks', 'arms', 'army', 'arts', 'arty', 'arum', 'arvo', 'aryl', 'asci', 'asea', 'ashy', 'asks', 'asps', 'atap', 'ates', 'atma', 'atom', 'atop',
      'auks', 'auld', 'aunt', 'aura', 'auto', 'aver', 'aves', 'avid', 'avos', 'avow', 'away', 'awed', 'awee', 'awes', 'awls', 'awns', 'awny', 'awol', 'awry', 'axal',
      'axed', 'axel', 'axes', 'axil', 'axis', 'axle', 'axon', 'ayah', 'ayes', 'ayin', 'azan', 'azon', 'baal', 'baas', 'baba', 'babe', 'babu', 'baby', 'bach', 'back',
      'bade', 'bads', 'baff', 'bags', 'baht', 'bail', 'bait', 'bake', 'bald', 'bale', 'balk', 'ball', 'balm', 'bals', 'bams', 'band', 'bane', 'bang', 'bani', 'bank',
      'bans', 'baps', 'barb', 'bard', 'bare', 'barf', 'bark', 'barm', 'barn', 'bars', 'base', 'bash', 'bask', 'bass', 'bast', 'bate', 'bath', 'bats', 'batt', 'baud',
      'bawd', 'bawl', 'bays', 'bead', 'beak', 'beam', 'bean', 'bear', 'beat', 'beau', 'beck', 'beds', 'bedu', 'beef', 'been', 'beep', 'beer', 'bees', 'beet', 'begs',
      'bell', 'bels', 'belt', 'bema', 'bend', 'bene', 'bens', 'bent', 'berg', 'berk', 'berm', 'best', 'beta', 'beth', 'bets', 'bevy', 'beys', 'bhut', 'bias', 'bibb',
      'bibs', 'bice', 'bide', 'bidi', 'bids', 'bier', 'biff', 'biga', 'bigs', 'bike', 'bile', 'bilk', 'bill', 'bima', 'bind', 'bine', 'bins', 'bint', 'biog', 'bios',
      'bird', 'birk', 'birl', 'biro', 'birr', 'bise', 'bisk', 'bite', 'bits', 'bitt', 'bize', 'blab', 'blae', 'blah', 'blam', 'blat', 'blaw', 'bleb', 'bled', 'blet',
      'blew', 'blin', 'blip', 'blob', 'bloc', 'blog', 'blot', 'blow', 'blub', 'blue', 'blur', 'boar', 'boas', 'boat', 'bobs', 'bock', 'bode', 'bods', 'body', 'boff',
      'bogs', 'bogy', 'boho', 'boil', 'bola', 'bold', 'bole', 'boll', 'bolo', 'bolt', 'bomb', 'bond', 'bone', 'bong', 'bonk', 'bony', 'book', 'boom', 'boon', 'boor',
      'boos', 'boot', 'bops', 'bora', 'bore', 'bork', 'born', 'bort', 'bosh', 'bosk', 'boss', 'bota', 'both', 'bots', 'bott', 'bout', 'bowl', 'bows', 'boxy', 'boyo',
      'boys', 'bozo', 'brad', 'brae', 'brag', 'bran', 'bras', 'brat', 'braw', 'bray', 'bred', 'bree', 'bren', 'brew', 'brie', 'brig', 'brim', 'brin', 'brio', 'bris',
      'brit', 'broo', 'bros', 'brow', 'brrr', 'brut', 'brux', 'bubo', 'bubs', 'bubu', 'buck', 'buds', 'buff', 'bugs', 'buhl', 'buhr', 'bulb', 'bulk', 'bull', 'bumf',
      'bump', 'bums', 'buna', 'bund', 'bung', 'bunk', 'bunn', 'buns', 'bunt', 'buoy', 'bura', 'burb', 'burd', 'burg', 'burl', 'burn', 'burp', 'burr', 'burs', 'bury',
      'bush', 'busk', 'buss', 'bust', 'busy', 'bute', 'buts', 'buys', 'buzz', 'byes', 'byre', 'byrl', 'byte', 'cabs', 'caca', 'cade', 'cadi', 'cads', 'cafe', 'caff',
      'cage', 'cagy', 'caid', 'cain', 'cake', 'caky', 'calf', 'calk', 'call', 'calm', 'calo', 'calx', 'came', 'camo', 'camp', 'cams', 'cane', 'cans', 'cant', 'cape',
      'caph', 'capo', 'caps', 'carb', 'card', 'care', 'cark', 'carl', 'carn', 'carp', 'carr', 'cars', 'cart', 'casa', 'case', 'cash', 'cask', 'cast', 'cate', 'cats',
      'caul', 'cave', 'cavy', 'caws', 'cays', 'ceca', 'cede', 'cedi', 'cees', 'ceil', 'cell', 'cels', 'celt', 'cent', 'cepe', 'ceps', 'cere', 'cero', 'cess', 'cete',
      'chad', 'chai', 'cham', 'chao', 'chap', 'char', 'chat', 'chaw', 'chay', 'chef', 'chew', 'chez', 'chia', 'chic', 'chid', 'chin', 'chip', 'chis', 'chit', 'chon',
      'chop', 'chow', 'chub', 'chug', 'chum', 'ciao', 'cigs', 'cine', 'cion', 'cire', 'cist', 'cite', 'city', 'clad', 'clag', 'clam', 'clan', 'clap', 'claw', 'clay',
      'clef', 'clew', 'clip', 'clod', 'clog', 'clon', 'clop', 'clot', 'cloy', 'club', 'clue', 'coal', 'coat', 'coax', 'cobb', 'cobs', 'coca', 'coco', 'coda', 'code',
      'cods', 'coed', 'coff', 'coft', 'cogs', 'coho', 'coif', 'coil', 'coin', 'coir', 'coke', 'coky', 'cola', 'cold', 'cole', 'cols', 'colt', 'coly', 'coma', 'comb',
      'come', 'comp', 'cone', 'coni', 'conk', 'conn', 'cons', 'cony', 'coof', 'cook', 'cool', 'coop', 'coos', 'coot', 'cope', 'cops', 'copy', 'cord', 'core', 'corf',
      'cork', 'corm', 'corn', 'cors', 'cory', 'cosh', 'coss', 'cost', 'cosy', 'cote', 'cots', 'coup', 'cove', 'cowl', 'cows', 'cowy', 'coxa', 'coys', 'cozy', 'crab',
      'brag', 'crag', 'cram', 'craw', 'cred', 'crew', 'crib', 'cris', 'crit', 'croc', 'crop', 'crow', 'crud', 'crus', 'crux', 'cube', 'cubs', 'cuds', 'cued', 'cues',
      'cuff', 'cuif', 'cuke', 'cull', 'culm', 'cult', 'cups', 'curb', 'curd', 'cure', 'curf', 'curl', 'curn', 'curr', 'curs', 'curt', 'cusk', 'cusp', 'cuss', 'cute',
      'cuts', 'cwms', 'cyan', 'cyma', 'cyme', 'cyst', 'czar', 'dabs', 'dace', 'dada', 'dado', 'dads', 'daff', 'daft', 'dago', 'dags', 'dahl', 'dahs', 'dais', 'daks',
      'dale', 'dals', 'dame', 'damp', 'dams', 'dang', 'dank', 'dans', 'daps', 'darb', 'dare', 'dark', 'darn', 'dart', 'dash', 'data', 'date', 'dato', 'daub', 'daut',
      'davy', 'dawk', 'dawn', 'daws', 'dawt', 'days', 'daze', 'dead', 'deaf', 'deal', 'dean', 'dear', 'debs', 'debt', 'deck', 'deco', 'deed', 'deem', 'deep', 'deer',
      'dees', 'deet', 'defi', 'deft', 'defy', 'deil', 'deke', 'dele', 'delf', 'deli', 'dell', 'dels', 'delt', 'deme', 'demo', 'demy', 'dene', 'deni', 'dens', 'dent',
      'deny', 'dere', 'derm', 'desk', 'deva', 'devs', 'dews', 'dewy', 'dexy', 'deys', 'dhak', 'dhal', 'dhow', 'dial', 'dibs', 'dice', 'dido', 'didy', 'died', 'diel',
      'dies', 'diet', 'diff', 'difs', 'digs', 'dike', 'dill', 'dime', 'dims', 'dine', 'ding', 'dino', 'dins', 'dint', 'diol', 'dips', 'dipt', 'dire', 'dirk', 'dirl',
      'dirt', 'disc', 'dish', 'diss', 'dita', 'dite', 'dits', 'ditz', 'diva', 'dive', 'djin', 'doat', 'doby', 'dock', 'docs', 'dodo', 'doer', 'does', 'doff', 'doge',
      'dogs', 'dogy', 'doit', 'dojo', 'dole', 'doll', 'dols', 'dolt', 'dome', 'doms', 'dona', 'done', 'dong', 'dons', 'doom', 'door', 'dopa', 'dope', 'dopy', 'dore',
      'dork', 'dorm', 'dorp', 'dorr', 'dors', 'dory', 'dose', 'doss', 'dost', 'dote', 'doth', 'dots', 'doty', 'doum', 'dour', 'doux', 'dove', 'down', 'dows', 'doxy',
      'doze', 'dozy', 'drab', 'drag', 'dram', 'drat', 'draw', 'dray', 'dree', 'dreg', 'drek', 'drew', 'drib', 'drip', 'drop', 'drub', 'drug', 'drum', 'drys', 'duad',
      'dual', 'dubs', 'duce', 'duci', 'duck', 'duct', 'dude', 'duds', 'duel', 'dues', 'duet', 'duff', 'dugs', 'duit', 'duke', 'dull', 'duly', 'duma', 'dumb', 'dump',
      'dune', 'dung', 'dunk', 'duns', 'dunt', 'duos', 'dupe', 'dups', 'dura', 'dure', 'durn', 'duro', 'durr', 'dusk', 'dust', 'duty', 'dyad', 'dyed', 'dyer', 'dyes',
      'dyne', 'each', 'earl', 'earn', 'ears', 'ease', 'east', 'easy', 'eath', 'eats', 'eaux', 'eave', 'ebbs', 'ebon', 'eche', 'echo', 'echt', 'ecru', 'ecus', 'eddo',
      'eddy', 'edge', 'edgy', 'edhs', 'edit', 'eels', 'eely', 'eery', 'effs', 'efts', 'egad', 'egal', 'eger', 'eggs', 'eggy', 'egis', 'egos', 'eide', 'eked', 'ekes',
      'elan', 'elds', 'elhi', 'elks', 'ells', 'elms', 'elmy', 'else', 'emes', 'emeu', 'emfs', 'emic', 'emir', 'emit', 'emmy', 'emus', 'emyd', 'ends', 'engs', 'enol',
      'enow', 'enuf', 'envy', 'eons', 'epee', 'epha', 'epic', 'epos', 'eras', 'ergo', 'ergs', 'erne', 'erns', 'eros', 'errs', 'erst', 'eses', 'esne', 'espy', 'etas',
      'etch', 'eths', 'etic', 'etna', 'etui', 'euro', 'even', 'ever', 'eves', 'evil', 'ewer', 'ewes', 'exam', 'exec', 'exed', 'exes', 'exit', 'exon', 'expo', 'eyas',
      'eyed', 'eyen', 'eyer', 'eyes', 'eyne', 'eyra', 'eyre', 'eyry', 'fabs', 'face', 'fact', 'fade', 'fado', 'fads', 'fail', 'fain', 'fair', 'fake', 'fall', 'falx',
      'fame', 'fane', 'fang', 'fano', 'fans', 'fard', 'fare', 'farl', 'farm', 'faro', 'fart', 'fash', 'fast', 'fate', 'fats', 'faun', 'faux', 'fava', 'fave', 'fawn',
      'fays', 'faze', 'feal', 'fear', 'feat', 'feds', 'feeb', 'feed', 'feel', 'fees', 'feet', 'fehs', 'fell', 'felt', 'feme', 'fems', 'fend', 'fens', 'feod', 'fere',
      'fern', 'fess', 'fest', 'feta', 'fete', 'fets', 'feud', 'feus', 'fiar', 'fiat', 'fibs', 'fice', 'fico', 'fido', 'fids', 'fief', 'fife', 'figs', 'fila', 'file',
      'fill', 'film', 'filo', 'fils', 'find', 'fine', 'fink', 'fino', 'fins', 'fire', 'firm', 'firn', 'firs', 'fisc', 'fish', 'fist', 'fits', 'five', 'fixt', 'fizz',
      'flab', 'flag', 'flak', 'flam', 'flan', 'flap', 'flat', 'flaw', 'flax', 'flay', 'flea', 'fled', 'flee', 'flew', 'flex', 'fley', 'flic', 'flip', 'flir', 'flit',
      'floc', 'floe', 'flog', 'flop', 'flow', 'flub', 'flue', 'flus', 'flux', 'foal', 'foam', 'fobs', 'foci', 'foes', 'fogs', 'fogy', 'fohn', 'foil', 'foin', 'fold',
      'folk', 'fond', 'fons', 'font', 'food', 'fool', 'foot', 'fops', 'fora', 'forb', 'ford', 'fore', 'fork', 'form', 'fort', 'foss', 'foul', 'four', 'fowl', 'foxy',
      'foys', 'fozy', 'frae', 'frag', 'frap', 'frat', 'fray', 'free', 'fret', 'frig', 'frit', 'friz', 'froe', 'frog', 'from', 'frow', 'frug', 'fubs', 'fuci', 'fuds',
      'fuel', 'fugs', 'fugu', 'fuji', 'full', 'fume', 'fumy', 'fund', 'funk', 'funs', 'furl', 'furs', 'fury', 'fuse', 'fuss', 'futz', 'fuze', 'fuzz', 'fyce', 'fyke',
      'gabs', 'gaby', 'gadi', 'gads', 'gaed', 'gaen', 'gaes', 'gaff', 'gaga', 'gage', 'gags', 'gain', 'gait', 'gala', 'gale', 'gall', 'gals', 'gama', 'gamb', 'game',
      'gamp', 'gams', 'gamy', 'gane', 'gang', 'gaol', 'gape', 'gaps', 'gapy', 'garb', 'gars', 'gash', 'gasp', 'gast', 'gate', 'gats', 'gaud', 'gaum', 'gaun', 'gaur',
      'gave', 'gawk', 'gawp', 'gays', 'gaze', 'gear', 'geck', 'geds', 'geed', 'geek', 'gees', 'geez', 'geld', 'gels', 'gelt', 'gems', 'gene', 'gens', 'gent', 'genu',
      'germ', 'gest', 'geta', 'gets', 'geum', 'ghat', 'ghee', 'ghis', 'gibe', 'gibs', 'gids', 'gied', 'gien', 'gies', 'gift', 'giga', 'gigs', 'gild', 'gill', 'gilt',
      'gimp', 'gink', 'gins', 'gips', 'gird', 'girl', 'girn', 'giro', 'girt', 'gist', 'gite', 'gits', 'give', 'glad', 'glam', 'gled', 'glee', 'gleg', 'glen', 'gley',
      'glia', 'glib', 'glim', 'glob', 'glom', 'glop', 'glow', 'glue', 'glug', 'glum', 'glut', 'gnar', 'gnat', 'gnaw', 'gnus', 'goad', 'goal', 'goas', 'goat', 'gobo',
      'gobs', 'goby', 'gods', 'goer', 'goes', 'gogo', 'gold', 'golf', 'gone', 'gong', 'good', 'goof', 'goon', 'goop', 'goos', 'gore', 'gorm', 'gorp', 'gory', 'gosh',
      'goth', 'gout', 'gowd', 'gowk', 'gown', 'goys', 'grab', 'grad', 'gram', 'gran', 'grat', 'gray', 'gree', 'grew', 'grey', 'grid', 'grig', 'grim', 'grin', 'grip',
      'grit', 'grog', 'grok', 'grot', 'grow', 'grub', 'grue', 'grum', 'guan', 'guar', 'guck', 'gude', 'guff', 'guid', 'gulf', 'gulf', 'gull', 'gulp', 'guls', 'gums',
      'gunk', 'guns', 'guru', 'gush', 'gust', 'guts', 'guvs', 'guys', 'gybe', 'gyms', 'gyps', 'gyre', 'gyri', 'gyro', 'gyve', 'haaf', 'haar', 'habu', 'hack', 'hade',
      'hadj', 'haed', 'haem', 'haen', 'haes', 'haet', 'haft', 'hags', 'haha', 'hahs', 'haik', 'hail', 'hair', 'haji', 'hajj', 'hake', 'haku', 'hale', 'half', 'hall',
      'halm', 'halo', 'halt', 'hame', 'hams', 'hand', 'hang', 'hank', 'hant', 'haps', 'hard', 'hare', 'hark', 'harl', 'harm', 'harp', 'hart', 'hash', 'hasp', 'hast',
      'hate', 'hath', 'hats', 'haul', 'haut', 'have', 'hawk', 'haws', 'hays', 'haze', 'hazy', 'head', 'heal', 'heap', 'hear', 'heat', 'hebe', 'heck', 'heed', 'heel',
      'heft', 'hehs', 'heil', 'heir', 'held', 'helm', 'helo', 'help', 'heme', 'hemi', 'hemp', 'hems', 'hens', 'hent', 'herb', 'herd', 'here', 'herl', 'herm', 'hern',
      'hero', 'hers', 'hest', 'heth', 'hets', 'hewn', 'hews', 'hick', 'hide', 'hied', 'hies', 'high', 'hike', 'hila', 'hili', 'hill', 'hilt', 'hims', 'hind', 'hins',
      'hint', 'hips', 'hire', 'hisn', 'hiss', 'hist', 'hits', 'hive', 'hoax', 'hobo', 'hobs', 'hock', 'hods', 'hoed', 'hoes', 'hogg', 'hogs', 'hoke', 'hold', 'hole',
      'holk', 'holm', 'holp', 'hols', 'holt', 'holy', 'home', 'homy', 'hone', 'hong', 'honk', 'hons', 'hood', 'hoof', 'hook', 'hoop', 'hoot', 'hope', 'hops', 'hora',
      'horn', 'hose', 'host', 'hots', 'hour', 'hove', 'howe', 'howf', 'howk', 'howl', 'hows', 'hoya', 'hoys', 'hubs', 'huck', 'hued', 'hues', 'huff', 'huge', 'hugs',
      'huic', 'hula', 'hulk', 'hull', 'hump', 'hums', 'hung', 'hunh', 'hunk', 'huns', 'hunt', 'hurl', 'hurt', 'hush', 'husk', 'huts', 'hwan', 'hyla', 'hymn', 'hype',
      'hypo', 'hyps', 'hyte', 'iamb', 'ibex', 'ibis', 'iced', 'ices', 'ichs', 'icky', 'icon', 'idea', 'idem', 'ides', 'idle', 'idly', 'idol', 'idyl', 'iffy', 'iggs',
      'iglu', 'ikat', 'ikon', 'ilea', 'ilex', 'ilia', 'ilka', 'ilks', 'ills', 'illy', 'imam', 'imid', 'immy', 'impi', 'imps', 'inby', 'inch', 'info', 'inia', 'inks',
      'inky', 'inly', 'inns', 'inro', 'inti', 'into', 'ions', 'iota', 'ired', 'ires', 'irid', 'iris', 'irks', 'iron', 'isba', 'isle', 'isms', 'itch', 'item', 'iter',
      'iwis', 'ixia', 'izar', 'jabs', 'jack', 'jade', 'jagg', 'jags', 'jail', 'jake', 'jamb', 'jams', 'jane', 'jape', 'jarl', 'jars', 'jato', 'jauk', 'jaup', 'java',
      'jaws', 'jays', 'jazz', 'jean', 'jeed', 'jeep', 'jeer', 'jees', 'jeez', 'jefe', 'jehu', 'jell', 'jeon', 'jerk', 'jess', 'jest', 'jete', 'jets', 'jeux', 'jews',
      'jiao', 'jibb', 'jibe', 'jibs', 'jiff', 'jigs', 'jill', 'jilt', 'jimp', 'jink', 'jinn', 'jins', 'jinx', 'jive', 'jivy', 'jobs', 'jock', 'joes', 'joey', 'jogs',
      'john', 'join', 'joke', 'joky', 'jole', 'jolt', 'josh', 'joss', 'jota', 'jots', 'jouk', 'jowl', 'jows', 'joys', 'juba', 'jube', 'juco', 'judo', 'juga', 'jugs',
      'juju', 'juke', 'juku', 'jump', 'junk', 'jupe', 'jura', 'jury', 'just', 'jute', 'juts', 'kaas', 'kabs', 'kadi', 'kaes', 'kafs', 'kagu', 'kaif', 'kail', 'kain',
      'kaka', 'kaki', 'kale', 'kame', 'kami', 'kana', 'kane', 'kaon', 'kapa', 'kaph', 'karn', 'kart', 'kata', 'kats', 'kava', 'kayo', 'kays', 'kbar', 'keas', 'keck',
      'keef', 'keek', 'keel', 'keen', 'keep', 'keet', 'kefs', 'kegs', 'keir', 'kelp', 'kelt', 'kemp', 'keno', 'kens', 'kent', 'kepi', 'keps', 'kept', 'kerb', 'kerf',
      'kern', 'keto', 'keys', 'khaf', 'khan', 'khat', 'khet', 'khis', 'kibe', 'kick', 'kids', 'kief', 'kier', 'kifs', 'kike', 'kill', 'kiln', 'kilo', 'kilt', 'kina',
      'kind', 'kine', 'king', 'kink', 'kino', 'kins', 'kips', 'kirk', 'kirn', 'kirs', 'kiss', 'kist', 'kite', 'kith', 'kits', 'kiva', 'kiwi', 'klik', 'knap', 'knar',
      'knee', 'knew', 'knit', 'knop', 'knot', 'know', 'knur', 'koan', 'koas', 'kobo', 'kobs', 'koel', 'kohl', 'kois', 'koji', 'kola', 'kolo', 'konk', 'kook', 'koph',
      'kops', 'kora', 'kore', 'kors', 'koss', 'koto', 'kris', 'kudo', 'kudu', 'kues', 'kufi', 'kuna', 'kune', 'kuru', 'kvas', 'kyak', 'kyar', 'kyes', 'kyte', 'labs',
      'lace', 'lack', 'lacs', 'lacy', 'lade', 'lads', 'lady', 'lags', 'laic', 'laid', 'lain', 'lair', 'lake', 'lakh', 'laky', 'lall', 'lama', 'lamb', 'lame', 'lamp',
      'lams', 'land', 'lane', 'lang', 'lank', 'laps', 'lard', 'lari', 'lark', 'lars', 'lase', 'lash', 'lass', 'last', 'late', 'lath', 'lati', 'lats', 'latu', 'laud',
      'lava', 'lave', 'lavs', 'lawn', 'laws', 'lays', 'laze', 'lazy', 'lead', 'leaf', 'leak', 'leal', 'lean', 'leap', 'lear', 'leas', 'lech', 'lede', 'leek', 'leer',
      'lees', 'leet', 'left', 'legs', 'lehr', 'leis', 'leke', 'leks', 'leku', 'lend', 'leno', 'lens', 'lent', 'lept', 'less', 'lest', 'lets', 'leud', 'leva', 'levo',
      'levy', 'lewd', 'leys', 'liar', 'libs', 'lice', 'lich', 'lick', 'lido', 'lids', 'lied', 'lief', 'lien', 'lier', 'lies', 'lieu', 'life', 'lift', 'like', 'lilo',
      'lilt', 'lily', 'lima', 'limb', 'lime', 'limn', 'limo', 'limp', 'limy', 'line', 'ling', 'link', 'linn', 'lino', 'lins', 'lint', 'liny', 'lion', 'lipa', 'lipe',
      'lips', 'lira', 'lire', 'liri', 'lisp', 'list', 'lite', 'lits', 'litu', 'live', 'load', 'loaf', 'loam', 'loan', 'lobe', 'lobo', 'lobs', 'loca', 'loch', 'loci',
      'lock', 'loco', 'lode', 'loft', 'loge', 'logo', 'logs', 'logy', 'loid', 'loin', 'loll', 'lone', 'long', 'loof', 'look', 'loom', 'loon', 'loop', 'loos', 'loot',
      'lope', 'lops', 'lord', 'lore', 'lorn', 'lory', 'lose', 'loss', 'lost', 'lota', 'loth', 'loti', 'lots', 'loud', 'loup', 'lour', 'lout', 'love', 'lowe', 'lown',
      'lows', 'luau', 'lube', 'luce', 'luck', 'lude', 'lues', 'luff', 'luge', 'lugs', 'lull', 'lulu', 'luma', 'lump', 'lums', 'luna', 'lune', 'lung', 'lunk', 'lunt',
      'luny', 'lure', 'lurk', 'lush', 'lute', 'lutz', 'luvs', 'luxe', 'lwei', 'lych', 'lyes', 'lynx', 'lyre', 'lyse', 'maar', 'mabe', 'mace', 'mach', 'mack', 'macs',
      'made', 'mads', 'maes', 'mage', 'magi', 'mags', 'maid', 'mail', 'maim', 'main', 'mair', 'make', 'mako', 'male', 'mall', 'malm', 'malt', 'mama', 'mana', 'mane',
      'mano', 'mans', 'many', 'maps', 'mara', 'marc', 'mare', 'mark', 'marl', 'mars', 'mart', 'masa', 'mash', 'mask', 'mass', 'mast', 'mate', 'math', 'mats', 'matt',
      'maud', 'maul', 'maun', 'maut', 'mawn', 'maws', 'maxi', 'maya', 'mayo', 'mays', 'maze', 'mazy', 'mead', 'meal', 'mean', 'meat', 'meds', 'meed', 'meek', 'meet',
      'mega', 'megs', 'meld', 'mell', 'mels', 'melt', 'meme', 'memo', 'mems', 'mend', 'meno', 'menu', 'meou', 'meow', 'merc', 'mere', 'merk', 'merl', 'mesa', 'mesh',
      'mess', 'meta', 'mete', 'meth', 'mewl', 'mews', 'meze', 'mhos', 'mibs', 'mica', 'mice', 'mick', 'mics', 'midi', 'mids', 'mien', 'miff', 'migg', 'migs', 'mike',
      'mild', 'mile', 'milk', 'mill', 'milo', 'mils', 'milt', 'mime', 'mina', 'mind', 'mine', 'mini', 'mink', 'mint', 'minx', 'mips', 'mire', 'miri', 'mirk', 'mirs',
      'miry', 'mise', 'miso', 'miss', 'mist', 'mite', 'mitt', 'mity', 'mixt', 'moan', 'moas', 'moat', 'mobs', 'mock', 'mocs', 'mode', 'modi', 'mods', 'mogs', 'moil',
      'mojo', 'moke', 'mola', 'mold', 'mole', 'moll', 'mols', 'molt', 'moly', 'mome', 'momi', 'moms', 'monk', 'mono', 'mons', 'mony', 'mood', 'mool', 'moon', 'moor',
      'moos', 'moot', 'mope', 'mops', 'mopy', 'mora', 'morn', 'mors', 'mort', 'mosh', 'mosk', 'moss', 'most', 'mote', 'moth', 'mots', 'mott', 'moue', 'move', 'mown',
      'mows', 'moxa', 'mozo', 'much', 'muck', 'muds', 'mugg', 'mugs', 'mule', 'mull', 'mumm', 'mump', 'mums', 'mumu', 'muni', 'muns', 'muon', 'mura', 'mure', 'murk',
      'murr', 'muse', 'mush', 'musk', 'muss', 'must', 'mute', 'muts', 'mutt', 'mycs', 'myna', 'myth', 'naan', 'nabe', 'nabs', 'nada', 'naff', 'nags', 'naif', 'nail',
      'nala', 'name', 'nana', 'nans', 'naoi', 'naos', 'napa', 'nape', 'naps', 'narc', 'nard', 'nark', 'nary', 'nave', 'navy', 'nays', 'neap', 'near', 'neat', 'nebs', 'neck',
      'need', 'neem', 'neep', 'negs', 'neif', 'nema', 'nene', 'neon', 'nerd', 'ness', 'nest', 'nets', 'nett', 'neuk', 'neum', 'neve', 'nevi', 'news', 'newt', 'next',
      'nibs', 'nice', 'nick', 'nide', 'nidi', 'nigh', 'nill', 'nils', 'nims', 'nine', 'nipa', 'nips', 'nisi', 'nite', 'nits', 'nixe', 'nixy', 'nobs', 'nock', 'node',
      'nodi', 'nods', 'noel', 'noes', 'nogg', 'nogs', 'noil', 'noir', 'nolo', 'noma', 'nome', 'noms', 'nona', 'none', 'nook', 'noon', 'nope', 'nori', 'norm', 'nose',
      'nosh', 'nosy', 'nota', 'note', 'noun', 'nous', 'nova', 'nows', 'nowt', 'nubs', 'nude', 'nuke', 'null', 'numb', 'nuns', 'nurd', 'nurl', 'nuts', 'oafs', 'oaks',
      'oaky', 'oars', 'oast', 'oath', 'oats', 'obas', 'obes', 'obey', 'obia', 'obis', 'obit', 'oboe', 'obol', 'ocas', 'odah', 'odas', 'odds', 'odea', 'odes', 'odic',
      'odor', 'odyl', 'ofay', 'offs', 'ogam', 'ogee', 'ogle', 'ogre', 'ohed', 'ohia', 'ohms', 'oils', 'oily', 'oink', 'okas', 'okay', 'okeh', 'okes', 'okra', 'olds',
      'oldy', 'olea', 'oleo', 'oles', 'olio', 'olla', 'omen', 'omer', 'omit', 'once', 'ones', 'only', 'onos', 'onto', 'onus', 'onyx', 'oohs', 'oops', 'oots', 'ooze',
      'oozy', 'opah', 'opal', 'oped', 'open', 'opes', 'opts', 'opus', 'orad', 'oral', 'orbs', 'orby', 'orca', 'orcs', 'ordo', 'ores', 'orgy', 'orle', 'orra', 'orts',
      'oryx', 'orzo', 'osar', 'oses', 'ossa', 'otic', 'otto', 'ouch', 'ouds', 'ouph', 'ours', 'oust', 'outs', 'ouzo', 'oval', 'oven', 'over', 'ovum', 'owed', 'owes',
      'owls', 'owns', 'owse', 'oxen', 'oxes', 'oxid', 'oxim', 'oyer', 'oyez', 'paca', 'pace', 'pack', 'pacs', 'pact', 'pacy', 'padi', 'pads', 'page', 'paid', 'paik',
      'pail', 'pain', 'pair', 'pale', 'pall', 'palm', 'palp', 'pals', 'paly', 'pams', 'pane', 'pang', 'pans', 'pant', 'papa', 'paps', 'para', 'pard', 'pare', 'park',
      'parr', 'pars', 'part', 'pase', 'pash', 'pass', 'past', 'pate', 'path', 'pats', 'paty', 'pave', 'pawl', 'paws', 'pays', 'peag', 'peak', 'peal', 'pean', 'pear',
      'peas', 'peat', 'pech', 'peck', 'pecs', 'peds', 'peed', 'peek', 'peel', 'peen', 'peep', 'peer', 'pees', 'pegs', 'pehs', 'pein', 'peke', 'pele', 'pelf', 'pelt',
      'pend', 'pens', 'pent', 'peon', 'pepo', 'peps', 'pere', 'peri', 'perk', 'perm', 'perp', 'pert', 'perv', 'peso', 'pest', 'pets', 'pews', 'pfft', 'pfui', 'phat',
      'phew', 'phis', 'phiz', 'phon', 'phot', 'phut', 'pial', 'pian', 'pias', 'pica', 'pice', 'pick', 'pics', 'pied', 'pier', 'pies', 'pigs', 'pika', 'pike', 'piki',
      'pile', 'pili', 'pill', 'pily', 'pima', 'pimp', 'pina', 'pine', 'ping', 'pink', 'pins', 'pint', 'piny', 'pion', 'pipe', 'pips', 'pipy', 'pirn', 'pish', 'piso',
      'pita', 'pith', 'pits', 'pity', 'pixy', 'plan', 'plat', 'play', 'plea', 'pleb', 'pled', 'plew', 'plex', 'plie', 'plod', 'plop', 'plot', 'plow', 'ploy', 'plug',
      'plum', 'plus', 'pock', 'poco', 'pods', 'poem', 'poet', 'pogy', 'pois', 'poke', 'poky', 'pole', 'poll', 'polo', 'pols', 'poly', 'pome', 'pomo', 'pomp', 'poms',
      'pond', 'pone', 'pong', 'pons', 'pony', 'pood', 'poof', 'pooh', 'pool', 'poon', 'poor', 'poos', 'poot', 'pope', 'pops', 'pore', 'pork', 'port', 'pose', 'posh',
      'post', 'posy', 'pots', 'pouf', 'pour', 'pout', 'pows', 'poxy', 'pram', 'prao', 'prat', 'prau', 'pray', 'pree', 'prep', 'prex', 'prey', 'prez', 'prig', 'prim',
      'proa', 'prod', 'prof', 'prog', 'prom', 'prop', 'pros', 'prow', 'psis', 'psst', 'ptui', 'pubs', 'puce', 'puck', 'puds', 'puff', 'pugh', 'pugs', 'puja', 'puke',
      'pula', 'pule', 'puli', 'pull', 'pulp', 'puls', 'puma', 'pump', 'puna', 'pung', 'punk', 'puns', 'punt', 'puny', 'pupa', 'pups', 'pupu', 'pure', 'puri', 'purl',
      'purr', 'purs', 'push', 'puss', 'puts', 'putt', 'putz', 'pyas', 'pyes', 'pyic', 'pyin', 'pyre', 'pyro', 'qadi', 'qaid', 'qats', 'qoph', 'quad', 'quag', 'quai',
      'quay', 'quey', 'quid', 'quin', 'quip', 'quit', 'quiz', 'quod', 'race', 'rack', 'racy', 'rads', 'raff', 'raft', 'raga', 'rage', 'ragg', 'ragi', 'rags', 'raia',
      'raid', 'rail', 'rain', 'rais', 'raja', 'rake', 'raki', 'raku', 'rale', 'rami', 'ramp', 'rams', 'rand', 'rang', 'rani', 'rank', 'rant', 'rape', 'raps', 'rapt',
      'rare', 'rase', 'rash', 'rasp', 'rate', 'rath', 'rato', 'rats', 'rave', 'raws', 'raya', 'rays', 'raze', 'razz', 'read', 'real', 'ream', 'reap', 'rear', 'rebs',
      'reck', 'recs', 'redd', 'rede', 'redo', 'reds', 'reed', 'reef', 'reek', 'reel', 'rees', 'refs', 'reft', 'regs', 'reif', 'rein', 'reis', 'rely', 'rems', 'rend',
      'rent', 'repo', 'repp', 'reps', 'resh', 'rest', 'rete', 'rets', 'revs', 'rhea', 'rhos', 'rhus', 'rial', 'rias', 'ribs', 'rice', 'rich', 'rick', 'ride', 'rids',
      'riel', 'rife', 'riff', 'rifs', 'rift', 'rigs', 'rile', 'rill', 'rime', 'rims', 'rimy', 'rind', 'ring', 'rink', 'rins', 'riot', 'ripe', 'rips', 'rise', 'risk',
      'rite', 'ritz', 'rive', 'road', 'roam', 'roan', 'roar', 'robe', 'robs', 'rock', 'rocs', 'rode', 'rods', 'roes', 'roil', 'role', 'rolf', 'roll', 'romp', 'roms',
      'rood', 'roof', 'rook', 'room', 'root', 'rope', 'ropy', 'rort', 'rose', 'rosy', 'rota', 'rote', 'roti', 'rotl', 'roto', 'rots', 'roue', 'roup', 'rout', 'roux',
      'rove', 'rows', 'rube', 'rubs', 'ruby', 'ruck', 'rudd', 'rude', 'rued', 'ruer', 'ruer', 'rues', 'ruff', 'ruga', 'rugs', 'ruin', 'rule', 'ruly', 'rump', 'rums',
      'rune', 'rung', 'runs', 'runt', 'ruse', 'rush', 'rusk', 'rust', 'ruth', 'ruts', 'ryas', 'ryes', 'ryke', 'rynd', 'ryot', 'sabe', 'sabs', 'sack', 'sacs', 'sade',
      'sadi', 'safe', 'saga', 'sage', 'sago', 'sags', 'sagy', 'said', 'sail', 'sain', 'sake', 'saki', 'sale', 'sall', 'salp', 'sals', 'salt', 'same', 'samp', 'sand',
      'sane', 'sang', 'sank', 'sans', 'saps', 'sard', 'sari', 'sark', 'sash', 'sass', 'sate', 'sati', 'saul', 'save', 'sawn', 'saws', 'says', 'scab', 'scad', 'scag',
      'scam', 'scan', 'scar', 'scat', 'scop', 'scot', 'scow', 'scry', 'scud', 'scum', 'scup', 'scut', 'seal', 'seam', 'sear', 'seas', 'seat', 'secs', 'sect', 'seed',
      'seek', 'seel', 'seem', 'seen', 'seep', 'seer', 'sees', 'sego', 'segs', 'seif', 'seis', 'self', 'sell', 'sels', 'seme', 'semi', 'send', 'sene', 'sent', 'sept',
      'sera', 'sere', 'serf', 'sers', 'seta', 'sets', 'sett', 'sewn', 'sews', 'sext', 'sexy', 'shad', 'shah', 'sham', 'shat', 'shaw', 'shay', 'shea', 'shed', 'shes',
      'shew', 'shim', 'shin', 'ship', 'shiv', 'shmo', 'shod', 'shoe', 'shog', 'shoo', 'shop', 'shot', 'show', 'shri', 'shul', 'shun', 'shwa', 'sial', 'sibb', 'sibs',
      'sice', 'sick', 'sics', 'side', 'sidh', 'sift', 'sigh', 'sign', 'sika', 'sike', 'sild', 'silk', 'sill', 'silo', 'silt', 'sima', 'simp', 'sims', 'sine', 'sing',
      'sinh', 'sink', 'sins', 'sipe', 'sips', 'sire', 'sirs', 'site', 'sith', 'sits', 'size', 'sizy', 'skag', 'skas', 'skat', 'skee', 'skeg', 'skep', 'skew', 'skid',
      'skim', 'skin', 'skip', 'skis', 'skit', 'skua', 'slab', 'slag', 'slam', 'slap', 'slat', 'slaw', 'slay', 'sled', 'slew', 'slid', 'slim', 'slip', 'slit', 'slob',
      'sloe', 'slog', 'slop', 'slot', 'slow', 'slub', 'slue', 'slug', 'slum', 'slur', 'smew', 'smit', 'smog', 'smug', 'snag', 'snap', 'snaw', 'sned', 'snib', 'snip',
      'snit', 'snob', 'snog', 'snot', 'snow', 'snub', 'snug', 'snye', 'soak', 'soap', 'soar', 'soba', 'sobs', 'soca', 'sock', 'soda', 'sods', 'sofa', 'soft', 'soil',
      'soja', 'soke', 'sola', 'sold', 'sole', 'soli', 'solo', 'sols', 'soma', 'some', 'soms', 'sone', 'song', 'sons', 'sook', 'soon', 'soot', 'soph', 'sops', 'sora',
      'sorb', 'sord', 'sore', 'sori', 'sorn', 'sort', 'soth', 'sots', 'souk', 'soul', 'soup', 'sour', 'sous', 'sown', 'sows', 'soya', 'soys', 'spae', 'spam', 'span',
      'spar', 'spas', 'spat', 'spay', 'spaz', 'spec', 'sped', 'spew', 'spik', 'spin', 'spit', 'spiv', 'spot', 'spry', 'spud', 'spue', 'spun', 'spur', 'sris', 'stab',
      'stag', 'star', 'stat', 'staw', 'stay', 'stem', 'step', 'stet', 'stew', 'stey', 'stir', 'stoa', 'stob', 'stop', 'stot', 'stow', 'stub', 'stud', 'stum', 'stun',
      'stye', 'suba', 'subs', 'such', 'suck', 'sudd', 'suds', 'sued', 'suer', 'sues', 'suet', 'sugh', 'suit', 'suks', 'sulk', 'sulu', 'sumo', 'sump', 'sums', 'sung',
      'sunk', 'sunn', 'suns', 'supe', 'sups', 'suqs', 'sura', 'surd', 'sure', 'surf', 'suss', 'swab', 'swag', 'swam', 'swan', 'swap', 'swat', 'sway', 'swig', 'swim',
      'swob', 'swop', 'swot', 'swum', 'sybo', 'syce', 'syke', 'syli', 'sync', 'syne', 'syph', 'tabs', 'tabu', 'tace', 'tach', 'tack', 'taco', 'tact', 'tads', 'tael',
      'tags', 'tahr', 'tail', 'tain', 'taka', 'take', 'tala', 'talc', 'tale', 'tali', 'talk', 'tall', 'tame', 'tamp', 'tams', 'tang', 'tank', 'tans', 'taos', 'tapa',
      'tape', 'taps', 'tare', 'tarn', 'taro', 'tarp', 'tars', 'tart', 'task', 'tass', 'tate', 'tats', 'taus', 'taut', 'tavs', 'taws', 'taxa', 'taxi', 'teak', 'teal',
      'team', 'tear', 'teas', 'teat', 'tech', 'teds', 'teed', 'teel', 'teem', 'teen', 'tees', 'teff', 'tegg', 'tegs', 'tela', 'tele', 'tell', 'tels', 'temp', 'tend',
      'tens', 'tent', 'tepa', 'term', 'tern', 'test', 'teth', 'tets', 'tews', 'text', 'thae', 'than', 'that', 'thaw', 'thee', 'them', 'then', 'thew', 'they', 'thin',
      'thio', 'thir', 'this', 'thou', 'thro', 'thru', 'thud', 'thug', 'thus', 'tick', 'tics', 'tide', 'tidy', 'tied', 'tier', 'ties', 'tiff', 'tike', 'tiki', 'tile',
      'till', 'tils', 'tilt', 'time', 'tine', 'ting', 'tins', 'tint', 'tiny', 'tipi', 'tips', 'tire', 'tirl', 'tiro', 'titi', 'tivy', 'toad', 'toby', 'tods', 'tody',
      'toea', 'toed', 'toes', 'toff', 'toft', 'tofu', 'toga', 'togs', 'toil', 'toit', 'toke', 'tola', 'told', 'tole', 'toll', 'tolu', 'tomb', 'tome', 'toms', 'tone',
      'tong', 'tons', 'tony', 'took', 'tool', 'toom', 'toon', 'toot', 'tope', 'toph', 'topi', 'topo', 'tops', 'tora', 'torc', 'tore', 'tori', 'torn', 'toro', 'torr',
      'tors', 'tort', 'tory', 'tosh', 'toss', 'tost', 'tote', 'tots', 'tour', 'tout', 'town', 'tows', 'towy', 'toyo', 'toys', 'trad', 'tram', 'trap', 'tray', 'tree',
      'tref', 'trek', 'tres', 'tret', 'trey', 'trig', 'trim', 'trio', 'trip', 'trod', 'trog', 'trop', 'trot', 'trow', 'troy', 'true', 'trug', 'tsar', 'tsks', 'tuba',
      'tube', 'tubs', 'tuck', 'tufa', 'tuff', 'tuft', 'tugs', 'tuis', 'tule', 'tump', 'tuna', 'tune', 'tung', 'tuns', 'tups', 'turf', 'turk', 'turn', 'tush', 'tusk',
      'tuts', 'tutu', 'twae', 'twas', 'twee', 'twig', 'twin', 'twit', 'twos', 'tyee', 'tyer', 'tyes', 'tyin', 'tyke', 'tyne', 'type', 'typo', 'typp', 'typy', 'tyre',
      'tyro', 'tzar', 'udon', 'udos', 'ughs', 'ugli', 'ugly', 'ukes', 'ulan', 'ulna', 'ulus', 'ulva', 'umbo', 'umps', 'unai', 'unau', 'unbe', 'unci', 'unco', 'unde',
      'undo', 'undy', 'unit', 'unto', 'upas', 'upby', 'updo', 'upon', 'urbs', 'urds', 'urea', 'urge', 'uric', 'urns', 'urps', 'ursa', 'urus', 'used', 'user', 'uses',
      'utas', 'utes', 'uvea', 'vacs', 'vagi', 'vail', 'vain', 'vair', 'vale', 'vamp', 'vane', 'vang', 'vans', 'vara', 'vars', 'vary', 'vasa', 'vase', 'vast', 'vats',
      'vatu', 'vaus', 'vavs', 'vaws', 'veal', 'veep', 'veer', 'vees', 'veil', 'vein', 'vela', 'veld', 'vena', 'vend', 'vent', 'vera', 'verb', 'vert', 'very', 'vest',
      'veto', 'vets', 'vext', 'vial', 'vibe', 'vice', 'vide', 'vids', 'vied', 'vier', 'vies', 'view', 'viga', 'vigs', 'vile', 'vill', 'vims', 'vina', 'vine', 'vino',
      'vins', 'viny', 'viol', 'virl', 'visa', 'vise', 'vita', 'viva', 'vive', 'voes', 'void', 'vole', 'volt', 'vote', 'vows', 'vrow', 'vugg', 'vugh', 'vugs', 'wabs',
      'wack', 'wade', 'wadi', 'wads', 'wady', 'waes', 'waff', 'waft', 'wage', 'wags', 'waif', 'wail', 'wain', 'wair', 'wait', 'wake', 'wale', 'walk', 'wall', 'waly',
      'wame', 'wand', 'wane', 'wans', 'want', 'wany', 'waps', 'ward', 'ware', 'wark', 'warm', 'warn', 'warp', 'wars', 'wart', 'wary', 'wash', 'wasp', 'wast', 'wats',
      'watt', 'wauk', 'waul', 'waur', 'wave', 'wavy', 'wawl', 'waws', 'waxy', 'ways', 'weak', 'weal', 'wean', 'wear', 'webs', 'weds', 'weed', 'week', 'weel', 'ween',
      'weep', 'weer', 'wees', 'weet', 'weft', 'weir', 'weka', 'weld', 'well', 'welt', 'wend', 'wens', 'went', 'wept', 'were', 'wert', 'west', 'wets', 'wham', 'whap',
      'what', 'whee', 'when', 'whet', 'whew', 'whey', 'whid', 'whig', 'whim', 'whin', 'whip', 'whir', 'whit', 'whiz', 'whoa', 'whom', 'whop', 'whup', 'whys', 'wich',
      'wick', 'wide', 'wife', 'wifi', 'wigs', 'wiki', 'wild', 'wile', 'will', 'wilt', 'wily', 'wimp', 'wind', 'wine', 'wing', 'wink', 'wino', 'wins', 'winy', 'wipe',
      'wire', 'wiry', 'wise', 'wish', 'wisp', 'wiss', 'wist', 'wite', 'with', 'wits', 'wive', 'woad', 'woes', 'wogs', 'woke', 'woks', 'wold', 'wolf', 'womb', 'wonk',
      'wons', 'wont', 'wood', 'woof', 'wool', 'woos', 'wops', 'word', 'wore', 'work', 'worm', 'worn', 'wort', 'wost', 'wots', 'wove', 'wows', 'wrap', 'wren', 'writ',
      'wuss', 'wych', 'wyes', 'wyle', 'wynd', 'wynn', 'wyns', 'wyte', 'xyst', 'yack', 'yaff', 'yagi', 'yags', 'yaks', 'yald', 'yams', 'yang', 'yank', 'yaps', 'yard',
      'yare', 'yarn', 'yaud', 'yaup', 'yawl', 'yawn', 'yawp', 'yaws', 'yays', 'yeah', 'yean', 'year', 'yeas', 'yech', 'yegg', 'yeld', 'yelk', 'yell', 'yelp', 'yens',
      'yeps', 'yerk', 'yeti', 'yett', 'yeuk', 'yews', 'yill', 'yins', 'yipe', 'yips', 'yird', 'yirr', 'ylem', 'yobs', 'yock', 'yodh', 'yods', 'yoga', 'yogh', 'yogi',
      'yoke', 'yoks', 'yolk', 'yond', 'yoni', 'yore', 'your', 'yous', 'yowe', 'yowl', 'yows', 'yoyo', 'yuan', 'yuca', 'yuch', 'yuck', 'yuga', 'yuks', 'yule', 'yups',
      'yurt', 'yutz', 'ywis', 'zags', 'zany', 'zaps', 'zarf', 'zeal', 'zebu', 'zeds', 'zees', 'zein', 'zeks', 'zeps', 'zerk', 'zero', 'zest', 'zeta', 'zigs', 'zill',
      'zinc', 'zine', 'zing', 'zins', 'zips', 'ziti', 'zits', 'zoea', 'zoic', 'zona', 'zone', 'zonk', 'zoom', 'zoon', 'zoos', 'zori', 'zouk', 'zyme']

c3 = ['aahed', 'aalii', 'aargh', 'abaca', 'abaci', 'aback', 'abaft', 'abaka', 'abamp', 'abase', 'abash', 'abate', 'abaya', 'abbas', 'abbes', 'abbey', 'abbot', 'abeam',
      'abele', 'abets', 'abhor', 'abide', 'abled', 'abler', 'ables', 'abmho', 'abode', 'abohm', 'aboil', 'aboma', 'aboon', 'abort', 'about', 'above', 'abris', 'abuse',
      'abuts', 'abuzz', 'abyes', 'abysm', 'abyss', 'acari', 'acerb', 'aceta', 'ached', 'aches', 'achoo', 'acids', 'acidy', 'acing', 'acini', 'ackee', 'acmes', 'acmic',
      'acned', 'acnes', 'acock', 'acold', 'acorn', 'acred', 'acres', 'acrid', 'acted', 'actin', 'actor', 'acute', 'acyls', 'adage', 'adapt', 'addax', 'added', 'adder',
      'addle', 'adeem', 'adept', 'adieu', 'adios', 'adits', 'adman', 'admen', 'admit', 'admix', 'adobe', 'adobo', 'adopt', 'adore', 'adorn', 'adown', 'adoze', 'adult',
      'adunc', 'adust', 'adyta', 'adzed', 'adzes', 'aecia', 'aedes', 'aegis', 'aeons', 'aerie', 'afars', 'affix', 'afire', 'afoam', 'afoot', 'afore', 'afoul', 'afrit',
      'after', 'again', 'agama', 'agape', 'agars', 'agate', 'agave', 'agaze', 'agene', 'agent', 'agers', 'agger', 'aggie', 'aggro', 'aghas', 'agile', 'aging', 'agios',
      'agism', 'agist', 'agita', 'aglee', 'aglet', 'agley', 'aglow', 'agmas', 'agone', 'agons', 'agony', 'agora', 'agree', 'agria', 'agues', 'ahead', 'ahing', 'ahold',
      'ahull', 'aided', 'aider', 'aides', 'ailed', 'aimed', 'aimer', 'aioli', 'aired', 'airer', 'airns', 'airth', 'airts', 'aisle', 'aitch', 'aiver', 'ajiva', 'ajuga',
      'akees', 'akela', 'akene', 'alack', 'alamo', 'aland', 'alane', 'alang', 'alans', 'alant', 'alarm', 'alary', 'alate', 'albas', 'album', 'alcid', 'alder', 'aldol',
      'alecs', 'alefs', 'aleph', 'alert', 'alfas', 'algae', 'algal', 'algas', 'algid', 'algin', 'algor', 'algum', 'alias', 'alibi', 'alien', 'alifs', 'align', 'alike',
      'aline', 'alist', 'alive', 'aliya', 'alkie', 'alkyd', 'alkyl', 'allay', 'allee', 'alley', 'allod', 'allot', 'allow', 'alloy', 'allyl', 'almah', 'almas', 'almeh',
      'almes', 'almud', 'almug', 'aloes', 'aloft', 'aloha', 'aloin', 'alone', 'along', 'aloof', 'aloud', 'alpha', 'altar', 'altho', 'altos', 'alula', 'alums', 'alure',
      'alway', 'amahs', 'amain', 'amass', 'amaze', 'amber', 'ambit', 'amble', 'ambos', 'ambry', 'ameba', 'ameer', 'amend', 'amens', 'ament', 'amias', 'amice', 'amici',
      'amide', 'amido', 'amids', 'amies', 'amiga', 'amigo', 'amine', 'amino', 'amins', 'amirs', 'amiss', 'amity', 'ammos', 'amnia', 'amnic', 'amnio', 'amoks', 'amole',
      'among', 'amort', 'amour', 'amped', 'ample', 'amply', 'ampul', 'amuck', 'amuse', 'amyls', 'ancho', 'ancon', 'andro', 'anear', 'anele', 'anent', 'angas', 'angel',
      'anger', 'angle', 'anglo', 'angry', 'angst', 'anile', 'anils', 'anima', 'anime', 'animi', 'anion', 'anise', 'ankhs', 'ankle', 'ankus', 'anlas', 'annal', 'annas',
      'annex', 'annoy', 'annul', 'anoas', 'anode', 'anole', 'anomy', 'ansae', 'antae', 'antas', 'anted', 'antes', 'antic', 'antis', 'antra', 'antre', 'antsy', 'anvil',
      'anyon', 'aorta', 'apace', 'apart', 'apeak', 'apeek', 'apers', 'apery', 'aphid', 'aphis', 'apian', 'aping', 'apish', 'apnea', 'apods', 'aport', 'appal', 'appel',
      'apple', 'apply', 'apres', 'apron', 'apses', 'apsis', 'apter', 'aptly', 'aquae', 'aquas', 'araks', 'arame', 'arbor', 'arced', 'arcus', 'ardeb', 'ardor', 'areae',
      'areal', 'areas', 'areca', 'areic', 'arena', 'arene', 'arepa', 'arete', 'argal', 'argil', 'argle', 'argol', 'argon', 'argot', 'argue', 'argus', 'arhat', 'arias',
      'ariel', 'arils', 'arise', 'arles', 'armed', 'armer', 'armet', 'armor', 'aroid', 'aroma', 'arose', 'arpen', 'arras', 'array', 'arris', 'arrow', 'arses', 'arsis',
      'arson', 'artal', 'artel', 'artsy', 'arums', 'arval', 'arvos', 'aryls', 'asana', 'ascot', 'ascus', 'asdic', 'ashed', 'ashen', 'ashes', 'aside', 'asked', 'asker',
      'askew', 'askoi', 'askos', 'aspen', 'asper', 'aspic', 'aspis', 'assai', 'assay', 'asset', 'aster', 'astir', 'asyla', 'ataps', 'ataxy', 'atilt', 'atlas', 'atman',
      'atmas', 'atoll', 'atoms', 'atomy', 'atone', 'atony', 'atopy', 'atria', 'atrip', 'attar', 'attic', 'audad', 'audio', 'audit', 'auger', 'aught', 'augur', 'aulic',
      'aunts', 'aunty', 'aurae', 'aural', 'aurar', 'auras', 'aurei', 'aures', 'auric', 'auris', 'aurum', 'autos', 'auxin', 'avail', 'avant', 'avast', 'avens', 'avers',
      'avert', 'avgas', 'avian', 'avion', 'aviso', 'avoid', 'avows', 'await', 'awake', 'award', 'aware', 'awash', 'awful', 'awing', 'awned', 'awoke', 'awols', 'axels',
      'axial', 'axile', 'axils', 'axing', 'axiom', 'axion', 'axite', 'axled', 'axles', 'axman', 'axmen', 'axone', 'axons', 'ayahs', 'ayins', 'azans', 'azide', 'azido',
      'azine', 'azlon', 'azoic', 'azole', 'azons', 'azote', 'azoth', 'azuki', 'azure', 'baaed', 'baals', 'babas', 'babel', 'babes', 'babka', 'baboo', 'babul', 'babus',
      'bacca', 'backs', 'bacon', 'baddy', 'badge', 'badly', 'baffs', 'baffy', 'bagel', 'baggy', 'bahts', 'bails', 'bairn', 'baith', 'baits', 'baiza', 'baize', 'baked',
      'baker', 'bakes', 'balas', 'balds', 'baldy', 'baled', 'baler', 'bales', 'balks', 'balky', 'bally', 'balms', 'balmy', 'balsa', 'banal', 'banco', 'banda', 'bands',
      'bandy', 'baned', 'banes', 'bangs', 'banjo', 'banks', 'banns', 'banty', 'barbe', 'barbs', 'barca', 'barde', 'bards', 'bared', 'barer', 'bares', 'barfs', 'barge',
      'baric', 'barks', 'barky', 'barms', 'barmy', 'barns', 'barny', 'baron', 'barre', 'barye', 'basal', 'based', 'baser', 'bases', 'basic', 'basil', 'basin', 'basis',
      'basks', 'bassi', 'basso', 'bassy', 'baste', 'basts', 'batch', 'bated', 'bates', 'bathe', 'baths', 'batik', 'baton', 'batts', 'battu', 'batty', 'bauds', 'baulk',
      'bawds', 'bawdy', 'bawls', 'bawty', 'bayed', 'bayou', 'bazar', 'bazoo', 'beach', 'beads', 'beady', 'beaks', 'beaky', 'beams', 'beamy', 'beano', 'beans', 'beard',
      'bears', 'beast', 'beats', 'beaus', 'beaut', 'beaux', 'bebop', 'becap', 'becks', 'bedel', 'bedew', 'bedim', 'beech', 'beedi', 'beefs', 'beefy', 'beeps', 'beers',
      'beery', 'beets', 'befit', 'befog', 'began', 'begat', 'beget', 'begin', 'begot', 'begum', 'begun', 'beige', 'beigy', 'being', 'belay', 'belch', 'belga', 'belie',
      'belle', 'bells', 'belly', 'belon', 'below', 'belts', 'bemas', 'bemix', 'bench', 'bends', 'bendy', 'benes', 'benne', 'benni', 'benny', 'bento', 'bents', 'beret',
      'bergs', 'berks', 'berme', 'berms', 'berry', 'berth', 'beryl', 'beses', 'beset', 'besom', 'besot', 'bests', 'betas', 'betel', 'beths', 'beton', 'betta', 'bevel',
      'bevor', 'bewig', 'bezel', 'bezil', 'bhang', 'bhoot', 'bhuts', 'biali', 'bialy', 'bibbs', 'bible', 'bicep', 'bices', 'biddy', 'bided', 'bider', 'bides', 'bidet',
      'bidis', 'bield', 'biers', 'biffs', 'biffy', 'bifid', 'biggy', 'bight', 'bigly', 'bigos', 'bigot', 'bijou', 'biked', 'biker', 'bikes', 'bikie', 'bilbo', 'bilby',
      'biles', 'bilge', 'bilgy', 'bilks', 'bills', 'billy', 'bimah', 'bimas', 'bimbo', 'binal', 'bindi', 'binds', 'biner', 'bines', 'binge', 'bingo', 'binit', 'bints',
      'biogs', 'biome', 'biont', 'biota', 'biped', 'bipod', 'birch', 'birds', 'birdy', 'birks', 'birle', 'birls', 'biros', 'birrs', 'birse', 'birth', 'bises', 'bisks',
      'bison', 'biter', 'bites', 'bitsy', 'bitts', 'bitty', 'bizes', 'blabs', 'black', 'blade', 'blaff', 'blahs', 'blain', 'blame', 'blams', 'bland', 'blank', 'blare',
      'blase', 'blast', 'blate', 'blats', 'blawn', 'blaws', 'blaze', 'bleak', 'blear', 'bleat', 'blebs', 'bleed', 'bleep', 'blend', 'blent', 'bless', 'blest', 'blets',
      'blimp', 'blimy', 'blind', 'bling', 'blini', 'blips', 'bliss', 'blite', 'blitz', 'bloat', 'blobs', 'block', 'blocs', 'blogs', 'bloke', 'blond', 'blood', 'bloom',
      'bloop', 'blots', 'blown', 'blows', 'blowy', 'blubs', 'blued', 'bluer', 'blues', 'bluet', 'bluey', 'bluff', 'blume', 'blunt', 'blurb', 'blurs', 'blurt', 'blush',
      'blype', 'board', 'boars', 'boart', 'boast', 'boats', 'bobby', 'bocce', 'bocci', 'boche', 'bocks', 'boded', 'bodes', 'boffo', 'boffs', 'bogan', 'bogey', 'boggy',
      'bogie', 'bogle', 'bogus', 'bohea', 'bohos', 'boils', 'boing', 'boink', 'boite', 'bokeh', 'bolar', 'bolas', 'bolds', 'boles', 'bolls', 'bolos', 'bolts', 'bolus',
      'bombe', 'bombs', 'bonds', 'boned', 'bones', 'boney', 'bongo', 'bongs', 'bonks', 'bonne', 'bonny', 'bonus', 'bonze', 'booby', 'boody', 'booed', 'boogy', 'books',
      'booms', 'boomy', 'boons', 'boors', 'boost', 'booth', 'boots', 'booty', 'booze', 'boozy', 'boral', 'boras', 'borax', 'bored', 'borer', 'bores', 'boric', 'borks',
      'borne', 'boron', 'borts', 'borty', 'bortz', 'bosks', 'bosky', 'bosom', 'boson', 'bossy', 'bosun', 'botas', 'botch', 'botel', 'bothy', 'botts', 'bough', 'boule',
      'bound', 'bourg', 'bourn', 'bouse', 'bousy', 'bouts', 'bovid', 'bowed', 'bowel', 'bower', 'bowls', 'bowse', 'boxed', 'boxer', 'boxes', 'boyar', 'boyla', 'boyos',
      'bozos', 'brace', 'brach', 'bract', 'brads', 'braes', 'brags', 'braid', 'brail', 'brain', 'brake', 'braky', 'brand', 'brank', 'brans', 'brant', 'brash', 'brass',
      'brats', 'brava', 'brave', 'bravi', 'bravo', 'brawl', 'brawn', 'braws', 'braxy', 'brays', 'braza', 'braze', 'bread', 'break', 'bream', 'brede', 'breed', 'brees',
      'brens', 'brent', 'breve', 'brews', 'briar', 'bribe', 'brick', 'bride', 'brief', 'brier', 'bries', 'brigs', 'brill', 'brims', 'brine', 'bring', 'brink', 'brins',
      'briny', 'brios', 'brisk', 'briss', 'brith', 'brits', 'britt', 'broad', 'brock', 'broil', 'broke', 'brome', 'bromo', 'bronc', 'brood', 'brook', 'broom', 'broos',
      'brose', 'brosy', 'broth', 'brown', 'brows', 'brugh', 'bruin', 'bruit', 'brume', 'brung', 'brunt', 'brush', 'brusk', 'brute', 'bruts', 'bubal', 'bubba', 'bubby',
      'bubus', 'bucko', 'bucks', 'buddy', 'budge', 'buffi', 'buffo', 'buffs', 'buffy', 'buggy', 'bugle', 'buhls', 'buhrs', 'build', 'built', 'bulbs', 'bulge', 'bulgy',
      'bulks', 'bulky', 'bulla', 'bulls', 'bully', 'bumfs', 'bumph', 'bumps', 'bumpy', 'bunas', 'bunch', 'bunco', 'bunds', 'bundt', 'bungs', 'bunko', 'bunks', 'bunns',
      'bunny', 'bunts', 'bunya', 'buoys', 'buppy', 'buran', 'buras', 'burbs', 'burds', 'buret', 'burgh', 'burgs', 'burin', 'burka', 'burke', 'burls', 'burly', 'burns',
      'burnt', 'burps', 'burqa', 'burro', 'burrs', 'burry', 'bursa', 'burse', 'burst', 'busby', 'bused', 'buses', 'bushy', 'busks', 'busts', 'busty', 'butch', 'buteo',
      'butes', 'butle', 'butte', 'butts', 'butty', 'butut', 'butyl', 'buxom', 'buyer', 'bwana', 'bylaw', 'byres', 'byrls', 'byssi', 'bytes', 'byway', 'cabal', 'cabby',
      'caber', 'cabin', 'cable', 'cabob', 'cacao', 'cacas', 'cache', 'cacti', 'caddy', 'cades', 'cadet', 'cadge', 'cadgy', 'cadis', 'cadre', 'caeca', 'cafes', 'caffs',
      'caged', 'cager', 'cages', 'cagey', 'cahow', 'caids', 'cains', 'caird', 'cairn', 'cajon', 'caked', 'cakes', 'cakey', 'calfs', 'calif', 'calix', 'calks', 'calla',
      'calls', 'calms', 'calos', 'calve', 'calyx', 'camas', 'camel', 'cameo', 'cames', 'camos', 'campi', 'campo', 'camps', 'campy', 'canal', 'candy', 'caned', 'caner',
      'canes', 'canid', 'canna', 'canny', 'canoe', 'canon', 'canso', 'canst', 'canto', 'cants', 'canty', 'caped', 'caper', 'capes', 'caphs', 'capiz', 'capon', 'capos',
      'caput', 'carat', 'carbo', 'carbs', 'cards', 'cared', 'carer', 'cares', 'caret', 'carex', 'cargo', 'carks', 'carle', 'carls', 'carns', 'carny', 'carob', 'carol',
      'carom', 'carpi', 'carps', 'carrs', 'carry', 'carse', 'carte', 'carts', 'carve', 'casas', 'cased', 'cases', 'casks', 'casky', 'caste', 'casts', 'casus', 'catch',
      'cater', 'cates', 'catty', 'cauld', 'caulk', 'cauls', 'cause', 'caved', 'caver', 'caves', 'cavie', 'cavil', 'cawed', 'cease', 'cebid', 'cecal', 'cecum', 'cedar',
      'ceded', 'ceder', 'cedes', 'cedis', 'ceiba', 'ceili', 'ceils', 'celeb', 'cella', 'celli', 'cello', 'cells', 'celom', 'celts', 'cense', 'cento', 'cents', 'centu',
      'ceorl', 'cepes', 'cerci', 'cered', 'ceres', 'ceria', 'ceric', 'ceros', 'cesta', 'cesti', 'cetes', 'chads', 'chafe', 'chaff', 'chain', 'chair', 'chais', 'chalk',
      'champ', 'chams', 'chang', 'chant', 'chaos', 'chape', 'chaps', 'chapt', 'chard', 'chare', 'chark', 'charm', 'charr', 'chars', 'chart', 'chary', 'chase', 'chasm',
      'chats', 'chaws', 'chays', 'cheap', 'cheat', 'check', 'cheek', 'cheep', 'cheer', 'chefs', 'chela', 'chemo', 'chert', 'chess', 'chest', 'cheth', 'chevy', 'chews',
      'chewy', 'chiao', 'chias', 'chica', 'chick', 'chico', 'chics', 'chide', 'chief', 'chiel', 'child', 'chile', 'chili', 'chill', 'chimb', 'chime', 'chimp', 'china',
      'chine', 'chino', 'chins', 'chips', 'chirk', 'chirm', 'chiro', 'chirp', 'chirr', 'chiru', 'chits', 'chive', 'chivy', 'chock', 'chode', 'choir', 'choke', 'choky',
      'chola', 'cholo', 'chomp', 'chook', 'chops', 'chord', 'chore', 'chose', 'chott', 'chows', 'chubs', 'chuck', 'chufa', 'chuff', 'chugs', 'chump', 'chums', 'chunk',
      'churl', 'churn', 'churr', 'chute', 'chyle', 'chyme', 'cibol', 'cider', 'cigar', 'cilia', 'cimex', 'cinch', 'cines', 'cions', 'circa', 'cires', 'cirri', 'cisco',
      'cissy', 'cists', 'cited', 'citer', 'cites', 'civet', 'civic', 'civie', 'civil', 'civvy', 'clach', 'clack', 'clade', 'clads', 'clags', 'claim', 'clamp', 'clams',
      'clang', 'clank', 'clans', 'claps', 'clapt', 'claro', 'clary', 'clash', 'clasp', 'class', 'clast', 'clave', 'clavi', 'claws', 'clays', 'clean', 'clear', 'cleat',
      'cleek', 'clefs', 'cleft', 'clepe', 'clept', 'clerk', 'clews', 'click', 'cliff', 'clift', 'climb', 'clime', 'cline', 'cling', 'clink', 'clips', 'clipt', 'cloak',
      'clock', 'clods', 'clogs', 'clomb', 'clomp', 'clone', 'clonk', 'clons', 'cloot', 'clops', 'close', 'cloth', 'clots', 'cloud', 'clour', 'clout', 'clove', 'clown',
      'cloys', 'cloze', 'clubs', 'cluck', 'clued', 'clues', 'clump', 'clung', 'clunk', 'cnida', 'coach', 'coact', 'coala', 'coals', 'coaly', 'coapt', 'coast', 'coati',
      'coats', 'cobbs', 'cobby', 'cobia', 'coble', 'cobra', 'cocas', 'cocci', 'cocky', 'cocoa', 'cocos', 'codas', 'codec', 'coded', 'coden', 'coder', 'codes', 'codex',
      'codon', 'coeds', 'coffs', 'cogon', 'cohog', 'cohos', 'coifs', 'coign', 'coils', 'coins', 'coirs', 'coked', 'cokes', 'colas', 'colby', 'colds', 'coled', 'coles',
      'colic', 'colin', 'colly', 'colog', 'colon', 'color', 'colts', 'colza', 'comae', 'comal', 'comas', 'combe', 'combo', 'combs', 'comer', 'comes', 'comet', 'comfy',
      'comic', 'comix', 'comma', 'commy', 'compo', 'comps', 'compt', 'comte', 'conch', 'condo', 'coned', 'cones', 'coney', 'conga', 'conge', 'congo', 'conic', 'conin',
      'conks', 'conky', 'conns', 'conte', 'conto', 'conus', 'cooch', 'cooed', 'cooee', 'cooer', 'cooey', 'coofs', 'cooks', 'cooky', 'cools', 'cooly', 'coomb', 'coons',
      'coops', 'coopt', 'coots', 'copal', 'copay', 'coped', 'copen', 'coper', 'copes', 'copra', 'copse', 'coral', 'corby', 'cords', 'cored', 'corer', 'cores', 'corgi',
      'coria', 'corks', 'corky', 'corms', 'corns', 'cornu', 'corny', 'corps', 'corse', 'cosec', 'coses', 'coset', 'cosey', 'cosie', 'costa', 'costs', 'cotan', 'coted',
      'cotes', 'cotta', 'couch', 'coude', 'cough', 'could', 'coupe', 'coups', 'court', 'couth', 'coved', 'coven', 'cover', 'coves', 'covet', 'covey', 'covin', 'cowed',
      'cower', 'cowls', 'cowry', 'coxae', 'coxal', 'coxed', 'coxes', 'coyed', 'coyer', 'coyly', 'coypu', 'cozen', 'cozes', 'cozey', 'cozie', 'craal', 'crabs', 'crack',
      'craft', 'crags', 'crake', 'cramp', 'crams', 'crane', 'crank', 'crape', 'craps', 'crash', 'crass', 'crate', 'crave', 'crawl', 'craws', 'craze', 'crazy', 'creak',
      'cream', 'credo', 'creds', 'creed', 'creek', 'creel', 'creep', 'creme', 'crepe', 'crept', 'crepy', 'cress', 'crest', 'crews', 'cribs', 'crick', 'cried', 'crier',
      'cries', 'crime', 'crimp', 'cripe', 'crisp', 'crits', 'croak', 'croci', 'crock', 'crocs', 'croft', 'crone', 'crony', 'crook', 'croon', 'crops', 'crore', 'cross',
      'croup', 'crowd', 'crown', 'crows', 'croze', 'cruck', 'crude', 'cruds', 'cruel', 'cruet', 'crumb', 'crump', 'cruor', 'crura', 'cruse', 'crush', 'crust', 'crwth',
      'crypt', 'cubby', 'cubeb', 'cubed', 'cuber', 'cubes', 'cubic', 'cubit', 'cuddy', 'cuffs', 'cuifs', 'cuing', 'cuish', 'cukes', 'culch', 'culet', 'culex', 'culls',
      'cully', 'culms', 'culpa', 'culti', 'cults', 'cumin', 'cupel', 'cupid', 'cuppa', 'cuppy', 'curbs', 'curch', 'curds', 'curdy', 'cured', 'curer', 'cures', 'curet',
      'curfs', 'curia', 'curie', 'curio', 'curls', 'curly', 'curns', 'currs', 'curry', 'curse', 'curst', 'curve', 'curvy', 'cusec', 'cushy', 'cusks', 'cusps', 'cusso',
      'cutch', 'cuter', 'cutes', 'cutey', 'cutie', 'cutin', 'cutis', 'cutty', 'cutup', 'cuvee', 'cyano', 'cyans', 'cyber', 'cycad', 'cycas', 'cycle', 'cyclo', 'cyder',
      'cylix', 'cymae', 'cymar', 'cymas', 'cymes', 'cymol', 'cynic', 'cysts', 'cyton', 'czars', 'daces', 'dacha', 'dadas', 'daddy', 'dados', 'daffs', 'daffy', 'dagga',
      'dagos', 'dahls', 'daily', 'dairy', 'daisy', 'dales', 'dally', 'daman', 'damar', 'dames', 'damns', 'damps', 'dance', 'dandy', 'dangs', 'danio', 'darbs', 'dared',
      'darer', 'dares', 'daric', 'darks', 'darky', 'darns', 'darts', 'dashi', 'dashy', 'dated', 'dater', 'dates', 'datos', 'datto', 'datum', 'daube', 'daubs', 'dauby',
      'daunt', 'dauts', 'daven', 'davit', 'dawed', 'dawen', 'dawks', 'dawns', 'dawts', 'dazed', 'dazes', 'deads', 'deair', 'deals', 'dealt', 'deans', 'dears', 'deary',
      'deash', 'death', 'deave', 'debag', 'debar', 'debit', 'debts', 'debug', 'debut', 'debye', 'decaf', 'decal', 'decay', 'decks', 'decor', 'decos', 'decoy', 'decry',
      'dedal', 'deeds', 'deedy', 'deems', 'deeps', 'deers', 'deets', 'defat', 'defer', 'defis', 'defog', 'degas', 'degum', 'deice', 'deify', 'deign', 'deils', 'deism',
      'deist', 'deity', 'deked', 'dekes', 'dekko', 'delay', 'deled', 'deles', 'delfs', 'delft', 'delis', 'dells', 'delly', 'delta', 'delts', 'delve', 'demes', 'demic',
      'demit', 'demob', 'demon', 'demos', 'demur', 'denar', 'denes', 'denim', 'dense', 'dents', 'deoxy', 'depot', 'depth', 'derat', 'deray', 'derby', 'derma', 'derms',
      'derry', 'desex', 'desks', 'deter', 'detox', 'deuce', 'devas', 'devel', 'devil', 'devon', 'dewan', 'dewar', 'dewax', 'dewed', 'dexes', 'dexie', 'dhaks', 'dhals',
      'dhobi', 'dhole', 'dhoti', 'dhows', 'dhuti', 'dials', 'diary', 'diazo', 'diced', 'dicer', 'dices', 'dicey', 'dicks', 'dicky', 'dicot', 'dicta', 'dicty', 'didie',
      'didos', 'didst', 'diene', 'diets', 'diffs', 'dight', 'digit', 'diked', 'diker', 'dikes', 'dikey', 'dills', 'dilly', 'dimer', 'dimes', 'dimly', 'dinar', 'dined',
      'diner', 'dines', 'dinge', 'dingo', 'dings', 'dingy', 'dinky', 'dinos', 'dints', 'diode', 'diols', 'dippy', 'dipso', 'diram', 'direr', 'dirge', 'dirks', 'dirls',
      'dirts', 'dirty', 'disci', 'disco', 'discs', 'dishy', 'disks', 'disme', 'ditas', 'ditch', 'dites', 'ditsy', 'ditto', 'ditty', 'ditzy', 'divan', 'divas', 'dived',
      'diver', 'dives', 'divot', 'divvy', 'diwan', 'dixie', 'dixit', 'dizen', 'dizzy', 'djinn', 'djins', 'doats', 'dobby', 'dobie', 'dobla', 'dobra', 'dobro', 'docks',
      'dodge', 'dodgy', 'dodos', 'doers', 'doest', 'doeth', 'doffs', 'doges', 'dogey', 'doggo', 'doggy', 'dogie', 'dogma', 'doily', 'doing', 'doits', 'dojos', 'dolce',
      'dolci', 'doled', 'doles', 'dolls', 'dolly', 'dolma', 'dolor', 'dolts', 'domal', 'domed', 'domes', 'domic', 'donas', 'donee', 'donga', 'dongs', 'donna', 'donne',
      'donor', 'donsy', 'donut', 'doody', 'dooly', 'dooms', 'doomy', 'doors', 'doozy', 'dopas', 'doped', 'doper', 'dopes', 'dopey', 'dorks', 'dorky', 'dorms', 'dormy',
      'dorps', 'dorrs', 'dorsa', 'dorty', 'dosed', 'doser', 'doses', 'dotal', 'doted', 'doter', 'dotes', 'dotty', 'doubt', 'douce', 'dough', 'doula', 'douma', 'doums',
      'doura', 'douse', 'doven', 'doves', 'dowdy', 'dowed', 'dowel', 'dower', 'dowie', 'downs', 'downy', 'dowry', 'dowse', 'doxie', 'doyen', 'doyly', 'dozed', 'dozen',
      'dozer', 'drabs', 'draff', 'draft', 'drags', 'drail', 'drain', 'drake', 'drama', 'drams', 'drank', 'drape', 'drats', 'drave', 'drawl', 'drawn', 'draws', 'drays',
      'dread', 'dream', 'drear', 'dreck', 'dreed', 'drees', 'dregs', 'dreks', 'dress', 'drest', 'dribs', 'dried', 'drier', 'dries', 'drift', 'drill', 'drily', 'drink',
      'drips', 'dript', 'drive', 'droid', 'droit', 'droll', 'drone', 'drool', 'droop', 'drops', 'dropt', 'dross', 'drouk', 'drove', 'drown', 'drubs', 'drugs', 'druid',
      'drums', 'drunk', 'drupe', 'druse', 'dryad', 'dryer', 'dryly', 'duads', 'duals', 'ducal', 'ducat', 'duces', 'duchy', 'ducks', 'ducky', 'ducts', 'duddy', 'duded',
      'dudes', 'duels', 'duets', 'duffs', 'dufus', 'duits', 'duked', 'dukes', 'dulia', 'dulls', 'dully', 'dulse', 'dumas', 'dumbo', 'dumbs', 'dumka', 'dumky', 'dummy',
      'dumps', 'dumpy', 'dunam', 'dunce', 'dunch', 'dunes', 'dungs', 'dungy', 'dunks', 'dunts', 'duomi', 'duomo', 'duped', 'duper', 'dupes', 'duple', 'dural', 'duras',
      'dured', 'dures', 'durns', 'duroc', 'duros', 'durra', 'durrs', 'durst', 'durum', 'dusks', 'dusky', 'dusts', 'dusty', 'dutch', 'duvet', 'dwarf', 'dweeb', 'dwell',
      'dwelt', 'dwine', 'dyads', 'dyers', 'dying', 'dyked', 'dykes', 'dykey', 'dynel', 'dynes', 'eager', 'eagle', 'eagre', 'eared', 'earls', 'early', 'earns', 'earth',
      'eased', 'easel', 'eases', 'easts', 'eaten', 'eater', 'eaved', 'eaves', 'ebbed', 'ebbet', 'ebola', 'ebons', 'ebony', 'ebook', 'eched', 'eches', 'echos', 'eclat',
      'ecrus', 'edema', 'edged', 'edger', 'edges', 'edict', 'edify', 'edile', 'edits', 'educe', 'educt', 'eerie', 'egads', 'egers', 'egest', 'eggar', 'egged', 'egger',
      'egret', 'eider', 'eidos', 'eight', 'eikon', 'eject', 'eking', 'elain', 'eland', 'elans', 'elate', 'elbow', 'elder', 'elect', 'elegy', 'elemi', 'elfin', 'elide',
      'elint', 'elite', 'eloin', 'elope', 'elude', 'elute', 'elver', 'elves', 'email', 'embar', 'embay', 'embed', 'ember', 'embow', 'emcee', 'emeer', 'emend', 'emery',
      'emeus', 'emirs', 'emits', 'emmer', 'emmet', 'emmys', 'emote', 'empty', 'emyde', 'emyds', 'enact', 'enate', 'ended', 'ender', 'endow', 'endue', 'enema', 'enemy',
      'enjoy', 'ennui', 'enoki', 'enols', 'enorm', 'enows', 'enrol', 'ensky', 'ensue', 'enter', 'entia', 'entry', 'enure', 'envoi', 'envoy', 'enzym', 'eosin', 'epact',
      'epees', 'ephah', 'ephas', 'ephod', 'ephor', 'epics', 'epoch', 'epode', 'epoxy', 'equal', 'equid', 'equip', 'erase', 'erect', 'ergot', 'erica', 'ernes', 'erode',
      'erose', 'erred', 'error', 'erses', 'eruct', 'erugo', 'erupt', 'ervil', 'escar', 'escot', 'eskar', 'esker', 'esnes', 'essay', 'esses', 'ester', 'estop', 'etape',
      'ether', 'ethic', 'ethos', 'ethyl', 'etnas', 'etude', 'etuis', 'etwee', 'etyma', 'euros', 'evade', 'evens', 'event', 'evert', 'every', 'evict', 'evils', 'evite',
      'evoke', 'ewers', 'exact', 'exalt', 'exams', 'excel', 'execs', 'exert', 'exile', 'exine', 'exing', 'exist', 'exits', 'exons', 'expat', 'expel', 'expos', 'extol',
      'extra', 'exude', 'exult', 'exurb', 'eyass', 'eyers', 'eying', 'eyras', 'eyres', 'eyrie', 'eyrir', 'fable', 'faced', 'facer', 'faces', 'facet', 'facia', 'facts',
      'faddy', 'faded', 'fader', 'fades', 'fadge', 'fados', 'faena', 'faery', 'faggy', 'fagin', 'fails', 'faint', 'fairs', 'fairy', 'faith', 'faked', 'faker', 'fakes',
      'fakey', 'fakir', 'falls', 'false', 'famed', 'fames', 'fancy', 'fanes', 'fanga', 'fangs', 'fanon', 'fanos', 'fanum', 'faqir', 'farad', 'farce', 'farci', 'farcy',
      'fards', 'fared', 'farer', 'fares', 'farle', 'farls', 'farms', 'faros', 'farts', 'fasts', 'fatal', 'fated', 'fates', 'fatly', 'fatso', 'fatty', 'fatwa', 'faugh',
      'fauld', 'fault', 'fauna', 'fauns', 'fauve', 'favas', 'faves', 'favor', 'favus', 'fawns', 'fawny', 'faxed', 'faxes', 'fayed', 'fazed', 'fazes', 'fears', 'fease',
      'feast', 'feats', 'feaze', 'fecal', 'feces', 'fecks', 'fedex', 'feebs', 'feeds', 'feels', 'feeze', 'feign', 'feint', 'feist', 'felid', 'fella', 'fells', 'felly',
      'felon', 'felts', 'femes', 'femme', 'femur', 'fence', 'fends', 'fenny', 'feods', 'feoff', 'feral', 'feres', 'feria', 'ferly', 'fermi', 'ferns', 'ferny', 'ferry',
      'fesse', 'fests', 'fetal', 'fetas', 'fetch', 'feted', 'fetes', 'fetid', 'fetor', 'fetus', 'feuar', 'feuds', 'feued', 'fever', 'fewer', 'feyer', 'feyly', 'fezes',
      'fezzy', 'fiars', 'fiats', 'fiber', 'fibre', 'fices', 'fiche', 'fichu', 'ficin', 'ficus', 'fidge', 'fidos', 'fiefs', 'field', 'fiend', 'fiery', 'fifed', 'fifer',
      'fifes', 'fifth', 'fifty', 'fight', 'filar', 'filch', 'filed', 'filer', 'files', 'filet', 'fille', 'fillo', 'fills', 'filly', 'filmi', 'films', 'filmy', 'filos',
      'filth', 'filum', 'final', 'finca', 'finch', 'finds', 'fined', 'finer', 'fines', 'finis', 'finks', 'finny', 'finos', 'fiord', 'fique', 'fired', 'firer', 'fires',
      'firms', 'firns', 'firry', 'first', 'firth', 'fiscs', 'fishy', 'fists', 'fitch', 'fitly', 'fiver', 'fives', 'fixed', 'fixer', 'fixes', 'fixit', 'fizzy', 'fjeld',
      'fjord', 'flabs', 'flack', 'flags', 'flail', 'flair', 'flake', 'flaky', 'flame', 'flams', 'flamy', 'flank', 'flans', 'flaps', 'flare', 'flash', 'flask', 'flats',
      'flaws', 'flawy', 'flaxy', 'flays', 'fleam', 'fleas', 'fleck', 'fleer', 'flees', 'fleet', 'flesh', 'flews', 'fleys', 'flick', 'flics', 'flied', 'flier', 'flies',
      'fling', 'flint', 'flips', 'flirs', 'flirt', 'flite', 'flits', 'float', 'flock', 'flocs', 'floes', 'flogs', 'flong', 'flood', 'floor', 'flops', 'flora', 'floss',
      'flota', 'flour', 'flout', 'flown', 'flows', 'flubs', 'flued', 'flues', 'fluff', 'fluid', 'fluke', 'fluky', 'flume', 'flump', 'flung', 'flunk', 'fluor', 'flush',
      'flute', 'fluty', 'fluyt', 'flyby', 'flyer', 'flyte', 'foals', 'foams', 'foamy', 'focal', 'focus', 'foehn', 'fogey', 'foggy', 'fogie', 'fohns', 'foils', 'foins',
      'foist', 'folds', 'foley', 'folia', 'folic', 'folio', 'folks', 'folly', 'fonds', 'fondu', 'fonts', 'foods', 'fools', 'foots', 'footy', 'foram', 'foray', 'forbs',
      'forby', 'force', 'fordo', 'fords', 'fores', 'forge', 'forgo', 'forks', 'forky', 'forme', 'forms', 'forte', 'forth', 'forts', 'forty', 'forum', 'fossa', 'fosse', 'fouls', 'found', 'fount', 'fours', 'fovea', 'fowls', 'foxed', 'foxes', 'foyer', 'frags', 'frail', 'frame', 'franc', 'frank',
      'fraps', 'frass', 'frats', 'fraud', 'frays', 'freak', 'freed', 'freer', 'frees', 'fremd', 'frena', 'frere', 'fresh', 'frets', 'friar', 'fried', 'frier', 'fries',
      'frigs', 'frill', 'frise', 'frisk', 'frith', 'frits', 'fritt', 'fritz', 'frizz', 'frock', 'froes', 'frogs', 'frond', 'frons', 'front', 'frore', 'frosh', 'frost',
      'froth', 'frown', 'frows', 'froze', 'frugs', 'fruit', 'frump', 'fryer', 'fubar', 'fubsy', 'fucus', 'fuddy', 'fudge', 'fuels', 'fugal', 'fuggy', 'fugio', 'fugle',
      'fugue', 'fugus', 'fujis', 'fulls', 'fully', 'fumed', 'fumer', 'fumes', 'fumet', 'fundi', 'funds', 'fungi', 'fungo', 'funks', 'funky', 'funny', 'furan', 'furls',
      'furor', 'furry', 'furze', 'furzy', 'fused', 'fusee', 'fusel', 'fuses', 'fusil', 'fussy', 'fusty', 'futon', 'fuzed', 'fuzee', 'fuzes', 'fuzil', 'fuzzy', 'fyces',
      'fykes', 'fytte', 'gabby', 'gable', 'gaddi', 'gadid', 'gadis', 'gadje', 'gadjo', 'gaffe', 'gaffs', 'gaged', 'gager', 'gages', 'gaily', 'gains', 'gaits', 'galah',
      'galas', 'galax', 'galea', 'gales', 'galls', 'gally', 'galop', 'gamas', 'gamay', 'gamba', 'gambe', 'gambs', 'gamed', 'gamer', 'games', 'gamey', 'gamic', 'gamin',
      'gamma', 'gammy', 'gamps', 'gamut', 'ganef', 'ganev', 'gangs', 'ganja', 'ganof', 'gaols', 'gaped', 'gaper', 'gapes', 'gappy', 'garbs', 'garda', 'garni', 'garth',
      'gases', 'gasps', 'gassy', 'gasts', 'gated', 'gater', 'gates', 'gator', 'gauds', 'gaudy', 'gauge', 'gault', 'gaums', 'gaunt', 'gaurs', 'gauss', 'gauze', 'gauzy',
      'gavel', 'gavot', 'gawks', 'gawky', 'gawps', 'gawsy', 'gayal', 'gayer', 'gayly', 'gazar', 'gazed', 'gazer', 'gazes', 'gazoo', 'gears', 'gecko', 'gecks', 'geeks',
      'geeky', 'geese', 'geest', 'gelds', 'gelee', 'gelid', 'gelts', 'gemma', 'gemmy', 'gemot', 'genes', 'genet', 'genic', 'genie', 'genii', 'genip', 'genoa', 'genom',
      'genre', 'genro', 'gents', 'genua', 'genus', 'geode', 'geoid', 'gerah', 'germs', 'germy', 'gesso', 'geste', 'gests', 'getas', 'getup', 'geums', 'ghast', 'ghats',
      'ghaut', 'ghazi', 'ghees', 'ghost', 'ghoul', 'ghyll', 'giant', 'gibed', 'giber', 'gibes', 'giddy', 'gifts', 'gigas', 'gighe', 'gigot', 'gigue', 'gilds', 'gills',
      'gilly', 'gilts', 'gimel', 'gimme', 'gimps', 'gimpy', 'ginks', 'ginny', 'ginzo', 'gipon', 'gipsy', 'girds', 'girls', 'girly', 'girns', 'giron', 'giros', 'girsh',
      'girth', 'girts', 'gismo', 'gists', 'gites', 'given', 'giver', 'gives', 'gizmo', 'glace', 'glade', 'glads', 'glady', 'glair', 'glams', 'gland', 'glans', 'glare',
      'glary', 'glass', 'glaze', 'glazy', 'gleam', 'glean', 'gleba', 'glebe', 'glede', 'gleds', 'gleed', 'gleek', 'glees', 'gleet', 'glens', 'gleys', 'glial', 'glias',
      'glide', 'gliff', 'glime', 'glims', 'glint', 'glitz', 'gloam', 'gloat', 'globe', 'globs', 'glogg', 'gloms', 'gloom', 'glops', 'glory', 'gloss', 'glost', 'glout',
      'glove', 'glows', 'gloze', 'glued', 'gluer', 'glues', 'gluey', 'glugs', 'glume', 'glums', 'gluon', 'glute', 'gluts', 'glyph', 'gnarl', 'gnarr', 'gnars', 'gnash',
      'gnats', 'gnawn', 'gnaws', 'gnome', 'goads', 'goals', 'goats', 'goban', 'gobos', 'godet', 'godly', 'goers', 'gofer', 'gogos', 'going', 'golds', 'golem', 'golfs',
      'golly', 'gombo', 'gomer', 'gonad', 'gonef', 'goner', 'gongs', 'gonia', 'gonif', 'gonof', 'gonzo', 'goods', 'goody', 'gooey', 'goofs', 'goofy', 'gooky', 'goons',
      'goony', 'goops', 'goopy', 'goose', 'goosy', 'gopik', 'goral', 'gored', 'gores', 'gorge', 'gorms', 'gorps', 'gorse', 'gorsy', 'goths', 'gouge', 'gourd', 'gouts',
      'gouty', 'gowan', 'gowds', 'gowks', 'gowns', 'goxes', 'goyim', 'graal', 'grabs', 'grace', 'grade', 'grads', 'graft', 'grail', 'grain', 'grama', 'gramp', 'grams',
      'grana', 'grand', 'grans', 'grant', 'grape', 'graph', 'grapy', 'grasp', 'grass', 'grate', 'grave', 'gravy', 'grays', 'graze', 'great', 'grego', 'greys', 'gride',
      'grids', 'grief', 'griff', 'grift', 'grigs', 'grill', 'grime', 'grimy', 'grind', 'grins', 'griot', 'gripe', 'grips', 'gript', 'gripy', 'grist', 'grith', 'grits',
      'groan', 'groat', 'grody', 'grogs', 'groin', 'groks', 'groom', 'grope', 'gross', 'grosz', 'grots', 'group', 'grout', 'grove', 'growl', 'grown', 'grows', 'grubs',
      'gruel', 'grues', 'gruff', 'grume', 'grump', 'grunt', 'guaco', 'guano', 'guans', 'guard', 'guars', 'guava', 'gucks', 'gudes', 'guess', 'guest', 'guffs', 'guide',
      'guids', 'guild', 'guile', 'guilt', 'guiro', 'guise', 'gulag', 'gular', 'gulch', 'gules', 'gulfs', 'gulfy', 'gulls', 'gully', 'gulps', 'gulpy', 'gumbo', 'gumma',
      'gummy', 'gunks', 'gunky', 'gunny', 'guppy', 'gurge', 'gurry', 'gursh', 'gurus', 'gushy', 'gussy', 'gusto', 'gusts', 'gusty', 'gutsy', 'gutta', 'gutty', 'guyed',
      'guyot', 'gwine', 'gybed', 'gybes', 'gyoza', 'gypsy', 'gyral', 'gyred', 'gyres', 'gyron', 'gyros', 'gyrus', 'gyved', 'gyves', 'haafs', 'haars', 'habit', 'habus',
      'hacek', 'hacks', 'hadal', 'haded', 'hades', 'hadji', 'hadst', 'haems', 'haets', 'hafis', 'hafiz', 'hafts', 'hahas', 'haika', 'haiks', 'haiku', 'hails', 'haint',
      'hairs', 'hairy', 'hajes', 'hajis', 'hajji', 'hakes', 'hakim', 'hakus', 'halal', 'haled', 'haler', 'hales', 'halid', 'hallo', 'halls', 'halma', 'halms', 'halon',
      'halos', 'halts', 'halva', 'halve', 'hamal', 'hames', 'hammy', 'hamza', 'hance', 'hands', 'handy', 'hangs', 'hanks', 'hanky', 'hansa', 'hanse', 'hants', 'haole',
      'hapax', 'haply', 'happy', 'hards', 'hardy', 'hared', 'harem', 'hares', 'harks', 'harls', 'harms', 'harps', 'harpy', 'harry', 'harsh', 'harts', 'hasps', 'haste',
      'hasty', 'hatch', 'hated', 'hater', 'hates', 'haugh', 'haulm', 'hauls', 'haunt', 'haute', 'haven', 'haver', 'haves', 'havoc', 'hawed', 'hawks', 'hawse', 'hayed',
      'hayer', 'hayey', 'hazan', 'hazed', 'hazel', 'hazer', 'hazes', 'heads', 'heady', 'heals', 'heaps', 'heapy', 'heard', 'hears', 'heart', 'heath', 'heats', 'heave',
      'heavy', 'hebes', 'hecks', 'heder', 'hedge', 'hedgy', 'heeds', 'heels', 'heeze', 'hefts', 'hefty', 'heigh', 'heils', 'heirs', 'heist', 'helio', 'helix', 'hello',
      'hells', 'helms', 'helos', 'helot', 'helps', 'helve', 'hemal', 'hemes', 'hemic', 'hemin', 'hemps', 'hempy', 'hence', 'henge', 'henna', 'henry', 'hents', 'herbs',
      'herby', 'herds', 'heres', 'herls', 'herma', 'herms', 'herns', 'heron', 'heros', 'herry', 'hertz', 'hests', 'heths', 'heuch', 'heugh', 'hewed', 'hewer', 'hexad',
      'hexed', 'hexer', 'hexes', 'hexyl', 'hicks', 'hided', 'hider', 'hides', 'highs', 'hight', 'hijab', 'hijra', 'hiked', 'hiker', 'hikes', 'hilar', 'hillo', 'hills',
      'hilly', 'hilts', 'hilum', 'hilus', 'hinds', 'hinge', 'hinky', 'hinny', 'hints', 'hiply', 'hippo', 'hippy', 'hired', 'hiree', 'hirer', 'hires', 'hissy', 'hists',
      'hitch', 'hived', 'hives', 'hoagy', 'hoard', 'hoars', 'hoary', 'hobby', 'hobos', 'hocks', 'hocus', 'hodad', 'hoers', 'hogan', 'hoggs', 'hoick', 'hoise', 'hoist',
      'hoked', 'hokes', 'holey', 'hokku', 'hokum', 'holds', 'holed', 'holes', 'holey', 'holks', 'holla', 'hollo', 'holly', 'holms', 'holts', 'homed', 'homer', 'homes',
      'homey', 'homie', 'homos', 'honan', 'honda', 'honed', 'honer', 'hones', 'honey', 'hongi', 'hongs', 'honks', 'honky', 'honor', 'hooch', 'hoods', 'hoody', 'hooey',
      'hoofs', 'hooka', 'hooks', 'hooky', 'hooly', 'hoops', 'hoots', 'hooty', 'hoped', 'hoper', 'hopes', 'hoppy', 'horah', 'horal', 'horas', 'horde', 'horns', 'horse',
      'horst', 'horsy', 'hosed', 'hosel', 'hosen', 'hoser', 'hoses', 'hosey', 'hosta', 'hosts', 'hotch', 'hotel', 'hotly', 'hound', 'houri', 'hours', 'house', 'hovel',
      'hover', 'howdy', 'howes', 'howff', 'howfs', 'howks', 'howls', 'hoyas', 'hoyle', 'hubby', 'hucks', 'huffs', 'huffy', 'huger', 'hulas', 'hulks', 'hulky', 'hullo',
      'hulls', 'human', 'humic', 'humid', 'humor', 'humph', 'humps', 'humpy', 'humus', 'hunch', 'hunks', 'hunky', 'hunts', 'hurds', 'hurls', 'hurly', 'hurry', 'hurst',
      'hurts', 'husks', 'husky', 'hussy', 'hutch', 'huzza', 'hydra', 'hydro', 'hyena', 'hying', 'hylas', 'hymen', 'hymns', 'hyoid', 'hyped', 'hyper', 'hypes', 'hypha',
      'hypos', 'hyrax', 'hyson', 'iambi', 'iambs', 'ichor', 'icier', 'icily', 'icing', 'icker', 'icons', 'ictic', 'ictus', 'ideal', 'ideas', 'idiom', 'idiot', 'idled',
      'idler', 'idles', 'idols', 'idyll', 'idyls', 'igged', 'igloo', 'ihram', 'ikats', 'ikons', 'ileac', 'ileal', 'ileum', 'ileus', 'iliac', 'iliad', 'ilial', 'ilium',
      'iller', 'image', 'imago', 'imams', 'imaum', 'imbed', 'imbue', 'imide', 'imido', 'imids', 'imine', 'imino', 'immix', 'imped', 'impel', 'impis', 'imply', 'inane',
      'inapt', 'inarm', 'inbox', 'inbye', 'incog', 'incur', 'incus', 'index', 'indie', 'indol', 'indow', 'indri', 'indue', 'inept', 'inert', 'infer', 'infix', 'infos',
      'infra', 'ingle', 'ingot', 'inion', 'inked', 'inker', 'inkle', 'inlay', 'inlet', 'inned', 'inner', 'input', 'inrun', 'inset', 'inter', 'intis', 'intro', 'inure',
      'inurn', 'invar', 'iodic', 'iodid', 'iodin', 'ionic', 'iotas', 'irade', 'irate', 'irids', 'iring', 'irked', 'iroko', 'irone', 'irons', 'irony', 'isbas', 'isled',
      'isles', 'islet', 'issei', 'issue', 'istle', 'itchy', 'items', 'ither', 'ivied', 'ivies', 'ivory', 'ixias', 'ixora', 'ixtle', 'izars', 'jabot', 'jacal', 'jacks',
      'jacky', 'jaded', 'jades', 'jager', 'jaggs', 'jaggy', 'jagra', 'jails', 'jakes', 'jalap', 'jalop', 'jambe', 'jambs', 'jammy', 'janes', 'janky', 'janty', 'japan',
      'japed', 'japer', 'japes', 'jarls', 'jatos', 'jauks', 'jaunt', 'jaups', 'javas', 'jawan', 'jawed', 'jazzy', 'jeans', 'jebel', 'jeeps', 'jeers', 'jefes', 'jehad',
      'jehus', 'jello', 'jells', 'jelly', 'jemmy', 'jenny', 'jerid', 'jerks', 'jerky', 'jerry', 'jesse', 'jests', 'jetes', 'jeton', 'jetty', 'jewel', 'jibbs', 'jibed',
      'jiber', 'jibes', 'jiffs', 'jiffy', 'jiggy', 'jihad', 'jills', 'jilts', 'jimmy', 'jimpy', 'jingo', 'jinks', 'jinni', 'jinns', 'jisms', 'jived', 'jiver', 'jives',
      'jivey', 'jnana', 'jocko', 'jocks', 'joeys', 'johns', 'joins', 'joint', 'joist', 'joked', 'joker', 'jokes', 'jokey', 'joles', 'jolly', 'jolts', 'jolty', 'jomon',
      'jones', 'joram', 'jorum', 'jotas', 'jotty', 'joual', 'jouks', 'joule', 'joust', 'jowar', 'jowed', 'jowls', 'jowly', 'joyed', 'jubas', 'jubes', 'jucos', 'judas',
      'judge', 'judos', 'jugal', 'jugum', 'juice', 'juicy', 'jujus', 'juked', 'jukes', 'jukus', 'julep', 'jumbo', 'jumps', 'jumpy', 'junco', 'junks', 'junky', 'junta',
      'junto', 'jupes', 'jupon', 'jural', 'jurat', 'jurel', 'juror', 'justs', 'jutes', 'jutty', 'kabab', 'kabar', 'kabob', 'kadis', 'kafir', 'kagus', 'kaiak', 'kaifs',
      'kails', 'kains', 'kakas', 'kakis', 'kalam', 'kales', 'kalif', 'kalpa', 'kames', 'kamik', 'kanas', 'kanes', 'kanji', 'kanzu', 'kaons', 'kapas', 'kaphs', 'kapok',
      'kappa', 'kaput', 'karat', 'karma', 'karns', 'karoo', 'karst', 'karts', 'kasha', 'katas', 'kauri', 'kaury', 'kavas', 'kayak', 'kayos', 'kazoo', 'kbars', 'kebab',
      'kebar', 'kebob', 'kecks', 'kedge', 'keefs', 'keeks', 'keels', 'keens', 'keeps', 'keets', 'keeve', 'kefir', 'keirs', 'kelep', 'kelim', 'kelly', 'kelps', 'kelpy',
      'kelts', 'kemps', 'kempt', 'kenaf', 'kench', 'kendo', 'kenos', 'kente', 'kepis', 'kerbs', 'kerfs', 'kerne', 'kerns', 'kerry', 'ketch', 'ketol', 'kevel', 'kevil',
      'kexes', 'keyed', 'khadi', 'khafs', 'khaki', 'khans', 'khaph', 'khats', 'kheda', 'kheth', 'khets', 'khoum', 'kiang', 'kibbe', 'kibbi', 'kibei', 'kibes', 'kibla',
      'kicks', 'kicky', 'kiddo', 'kiddy', 'kiefs', 'kiers', 'kikes', 'kilim', 'kills', 'kilns', 'kilos', 'kilts', 'kilty', 'kinas', 'kinds', 'kines', 'kings', 'kinin',
      'kinks', 'kinky', 'kinos', 'kiosk', 'kirks', 'kirns', 'kissy', 'kists', 'kited', 'kiter', 'kites', 'kithe', 'kiths', 'kitty', 'kivas', 'kiwis', 'klick', 'kliks',
      'klong', 'kloof', 'kluge', 'klutz', 'knack', 'knaps', 'knars', 'knaur', 'knave', 'knawe', 'knead', 'kneed', 'kneel', 'knees', 'knell', 'knelt', 'knife', 'knish',
      'knits', 'knobs', 'knock', 'knoll', 'knops', 'knosp', 'knots', 'knout', 'known', 'knows', 'knurl', 'knurs', 'koala', 'koans', 'kobos', 'koels', 'kohls', 'koine',
      'kojis', 'kolas', 'kolos', 'kombu', 'konks', 'kooks', 'kooky', 'kopek', 'kophs', 'kopje', 'koppa', 'korai', 'koras', 'korat', 'korma', 'korun', 'kotos', 'kotow',
      'kraal', 'kraft', 'krait', 'kraut', 'kreep', 'krewe', 'krill', 'krona', 'krone', 'kroon', 'krubi', 'kudos', 'kudus', 'kudzu', 'kufis', 'kugel', 'kukri', 'kulak',
      'kumys', 'kurta', 'kurus', 'kusso', 'kvass', 'kvell', 'kyack', 'kyaks', 'kyars', 'kylix', 'kyrie', 'kytes', 'kythe', 'laari', 'label', 'labor', 'labra', 'laced',
      'lacer', 'laces', 'lacey', 'lacks', 'laded', 'laden', 'lader', 'lades', 'ladle', 'laevo', 'lagan', 'lahar', 'laich', 'laics', 'laigh', 'laird', 'lairs',
      'laith', 'laity', 'laked', 'laker', 'lakes', 'lakhs', 'lalls', 'lamas', 'lambs', 'lamby', 'lamed', 'lamer', 'lames', 'lamia', 'lamps', 'lanai', 'lance',
      'lands', 'lanes', 'lanky', 'lapel', 'lapin', 'lapis', 'lapse', 'larch', 'lards', 'lardy', 'laree', 'lares', 'large', 'largo', 'laris', 'larks', 'larky',
      'larum', 'larva', 'lased', 'laser', 'lases', 'lassi', 'lasso', 'lasts', 'latch', 'lated', 'laten', 'later', 'latex', 'lathe', 'lathi', 'laths', 'lathy',
      'latke', 'latte', 'lauan', 'lauds', 'laugh', 'laura', 'lavas', 'laved', 'laver', 'laves', 'lawed', 'lawns', 'lawny', 'laxer', 'laxes', 'laxly', 'layed',
      'layer', 'layin', 'layup', 'lazar', 'lazed', 'lazes', 'leach', 'leads', 'leady', 'leafs', 'leafy', 'leaks', 'leaky', 'leans', 'leant', 'leaps', 'leapt',
      'learn', 'lears', 'leary', 'lease', 'leash', 'least', 'leave', 'leavy', 'leben', 'ledge', 'ledgy', 'leech', 'leeks', 'leers', 'leery', 'leets', 'lefts',
      'lefty', 'legal', 'leger', 'leges', 'leggy', 'legit', 'lehrs', 'lehua', 'leman', 'lemma', 'lemon', 'lemur', 'lends', 'lenes', 'lenis', 'lenos', 'lense',
      'lento', 'leone', 'leper', 'lepta', 'lesbo', 'leses', 'letch', 'lethe', 'letup', 'leuds', 'levee', 'level', 'lever', 'levin', 'levis', 'lewis', 'lexes',
      'lexis', 'lezes', 'lezzy', 'liana', 'liane', 'liang', 'liard', 'liars', 'libel', 'liber', 'libra', 'libri', 'lichi', 'licht', 'licit', 'licks', 'lidar',
      'lidos', 'liege', 'liens', 'liers', 'lieus', 'lieve', 'lifer', 'lifts', 'ligan', 'liger', 'light', 'liked', 'liken', 'liker', 'likes', 'lilac', 'lilos',
      'lilts', 'liman', 'limas', 'limba', 'limbi', 'limbo', 'limbs', 'limby', 'limed', 'limen', 'limes', 'limey', 'limit', 'limns', 'limos', 'limpa', 'limps',
      'linac', 'lindy', 'lined', 'linen', 'liner', 'lines', 'liney', 'linga', 'lingo', 'lings', 'lingy', 'linin', 'links', 'linky', 'linns', 'linos', 'lints',
      'linty', 'linum', 'lions', 'lipas', 'lipid', 'lipin', 'lippy', 'liras', 'lirot', 'lisle', 'lisps', 'lists', 'litai', 'litas', 'liter', 'lithe', 'litho',
      'litre', 'lived', 'liven', 'liver', 'lives', 'livid', 'livre', 'llama', 'llano', 'loach', 'loads', 'loafs', 'loams', 'loamy', 'loans', 'loath', 'lobar',
      'lobby', 'lobed', 'lobes', 'lobos', 'local', 'lochs', 'locks', 'locos', 'locum', 'locus', 'loden', 'lodes', 'lodge', 'loess', 'lofts', 'lofty', 'logan',
      'loges', 'loggy', 'logia', 'logic', 'login', 'logoi', 'logon', 'logos', 'loids', 'loins', 'lolls', 'lolly', 'loner', 'longe', 'longs', 'looby', 'looed',
      'looey', 'loofa', 'loofs', 'looie', 'looks', 'looms', 'loons', 'loony', 'loops', 'loopy', 'loose', 'loots', 'loped', 'loper', 'lopes', 'loppy', 'loral',
      'loran', 'lords', 'lores', 'loris', 'lorry', 'losel', 'loser', 'loses', 'lossy', 'lotah', 'lotas', 'lotic', 'lotos', 'lotte', 'lotos', 'lotus', 'lough',
      'louie', 'louma', 'loupe', 'loups', 'lours', 'loury', 'louse', 'lousy', 'louts', 'lovat', 'loved', 'lover', 'loves', 'lowed', 'lower', 'lowes', 'lowly',
      'lowse', 'loxed', 'loxes', 'loyal', 'luaus', 'lubed', 'lubes', 'luces', 'lucid', 'lucks', 'lucky', 'lucre', 'ludes', 'ludic', 'luffa', 'luffs', 'luged',
      'luger', 'luges', 'lulls', 'lulus', 'lumas', 'lumen', 'lumps', 'lumpy', 'lunar', 'lunas', 'lunch', 'lunes', 'lunet', 'lunge', 'lungi', 'lungs', 'lunks',
      'lunts', 'lupin', 'lupus', 'lurch', 'lured', 'lurer', 'lures', 'lurex', 'lurid', 'lurks', 'lusts', 'lusty', 'lusus', 'lutea', 'luted', 'lutes', 'luxes',
      'lweis', 'lyard', 'lyart', 'lyase', 'lycea', 'lycee', 'lycra', 'lying', 'lymph', 'lynch', 'lyres', 'lyric', 'lysed', 'lyses', 'lysin', 'lysis', 'lyssa',
      'lytic', 'lytta', 'maars', 'mabes', 'macaw', 'maced', 'macer', 'maces', 'mache', 'macho', 'machs', 'macks', 'macle', 'macon', 'macro', 'madam', 'madly',
      'madre', 'mafia', 'mafic', 'mages', 'magic', 'magma', 'magot', 'magus', 'mahoe', 'maids', 'maile', 'maill', 'mails', 'maims', 'mains', 'mairs', 'maist',
      'maize', 'major', 'makar', 'maker', 'makes', 'makos', 'malar', 'males', 'malic', 'malls', 'malms', 'malmy', 'malts', 'malty', 'mamas', 'mamba', 'mambo',
      'mamey', 'mamie', 'mamma', 'mammy', 'manas', 'manat', 'maned', 'manes', 'manga', 'mange', 'mango', 'mangy', 'mania', 'manic', 'manly', 'manna', 'manor',
      'manos', 'manse', 'manta', 'manus', 'maple', 'maqui', 'maras', 'march', 'marcs', 'mares', 'marge', 'maria', 'marka', 'marks', 'marls', 'marly', 'marry',
      'marse', 'marsh', 'marts', 'marvy', 'masas', 'maser', 'mashy', 'masks', 'mason', 'massa', 'masse', 'massy', 'masts', 'match', 'mated', 'mater', 'mates',
      'matey', 'maths', 'matin', 'matte', 'matts', 'matza', 'matzo', 'mauds', 'mauls', 'maund', 'mauts', 'mauve', 'maven', 'mavie', 'mavin', 'mavis', 'mawed',
      'maxed', 'maxes', 'maxim', 'maxis', 'mayan', 'mayas', 'maybe', 'mayed', 'mayor', 'mayos', 'mayst', 'mazed', 'mazer', 'mazes', 'mbira', 'meads', 'meals',
      'mealy', 'means', 'meant', 'meany', 'meats', 'meaty', 'mecca', 'medal', 'media', 'medic', 'medii', 'meeds', 'meets', 'meiny', 'melds', 'melee', 'melic',
      'mells', 'melon', 'melts', 'melty', 'memes', 'memos', 'menad', 'mends', 'mensa', 'mense', 'mensh', 'menta', 'menus', 'meous', 'meows', 'merch', 'mercs',
      'mercy', 'merde', 'merer', 'meres', 'merge', 'merit', 'merks', 'merle', 'merls', 'merry', 'mesas', 'meshy', 'mesic', 'mesne', 'meson', 'messy', 'metal',
      'meted', 'meter', 'metes', 'meths', 'metis', 'metol', 'metre', 'metro', 'mewed', 'mewls', 'mezes', 'mezzo', 'miaou', 'miaow', 'miasm', 'miaul', 'micas',
      'miche', 'micks', 'micra', 'micro', 'middy', 'midge', 'midis', 'midst', 'miens', 'miffs', 'miffy', 'miggs', 'might', 'miked', 'mikes', 'mikra', 'milch',
      'milds', 'miler', 'miles', 'milia', 'milks', 'milky', 'mille', 'mills', 'milos', 'milpa', 'milts', 'milty', 'mimed', 'mimeo', 'mimer', 'mimes', 'mimic',
      'minae', 'minas', 'mince', 'mincy', 'minds', 'mined', 'miner', 'mines', 'mingy', 'minim', 'minis', 'minke', 'minks', 'minny', 'minor', 'mints', 'minty',
      'minus', 'mired', 'mires', 'mirex', 'mirid', 'mirin', 'mirks', 'mirky', 'mirth', 'mirza', 'misdo', 'miser', 'mises', 'misos', 'missy', 'mists', 'misty',
      'miter', 'mites', 'mitis', 'mitre', 'mitts', 'mixed', 'mixer', 'mixes', 'mixup', 'mizen', 'moans', 'moats', 'mocha', 'mocks', 'modal', 'model', 'modem',
      'modes', 'modus', 'moggy', 'mogul', 'mohel', 'mohur', 'moils', 'moira', 'moire', 'moist', 'mojos', 'mokes', 'molal', 'molar', 'molas', 'molds', 'moldy',
      'moles', 'molls', 'molly', 'molto', 'molts', 'momes', 'momma', 'mommy', 'momus', 'monad', 'monas', 'monde', 'mondo', 'money', 'mongo', 'monie', 'monks',
      'monos', 'monte', 'month', 'mooch', 'moods', 'moody', 'mooed', 'moola', 'mools', 'moons', 'moony', 'moors', 'moory', 'moose', 'moots', 'moped', 'moper',
      'mopes', 'mopey', 'morae', 'moral', 'moras', 'moray', 'morel', 'mores', 'morns', 'moron', 'morph', 'morro', 'morse', 'morts', 'mosey', 'mosks', 'mosso',
      'mossy', 'moste', 'mosts', 'motel', 'motes', 'motet', 'motey', 'moths', 'mothy', 'motif', 'motor', 'motte', 'motto', 'motts', 'mouch', 'moues', 'mould',
      'moult', 'mound', 'mount', 'mourn', 'mouse', 'mousy', 'mouth', 'moved', 'mover', 'moves', 'movie', 'mowed', 'mowes', 'moxas', 'moxie', 'mozos', 'mucho',
      'mucid', 'mucin', 'mucks', 'mucky', 'mucor', 'mucro', 'mucus', 'muddy', 'mudra', 'muffs', 'mufti', 'muggs', 'muggy', 'muhly', 'mujik', 'mulch', 'mulct',
      'muled', 'mules', 'muley', 'mulla', 'mulls', 'multi', 'mumms', 'mummy', 'mumps', 'mumus', 'munch', 'mungo', 'munis', 'muons', 'mural', 'muras', 'mured',
      'mures', 'murex', 'murid', 'murks', 'murky', 'murra', 'murre', 'murrs', 'murry', 'musca', 'mused', 'muser', 'muses', 'mushy', 'music', 'musks', 'musky',
      'mussy', 'musth', 'musts', 'musty', 'mutch', 'muted', 'muter', 'mutes', 'muton', 'mutts', 'muzzy', 'mylar', 'mynah', 'mynas', 'myoid', 'myoma', 'myope',
      'myopy', 'myrrh', 'mysid', 'myths', 'mythy', 'naans', 'nabes', 'nabis', 'nabob', 'nacho', 'nacre', 'nadas', 'nadir', 'naevi', 'naffs', 'naggy', 'naiad',
      'naifs', 'nails', 'naira', 'nairu', 'naive', 'nakfa', 'nalas', 'naled', 'named', 'namer', 'names', 'nanas', 'nance', 'nancy', 'nanny', 'napas', 'napes',
      'nappa', 'nappe', 'nappy', 'marco', 'narcs', 'nards', 'natch', 'nates', 'natty', 'naval', 'navar', 'navel', 'naves', 'navvy', 'nawab', 'neaps', 'nears',
      'neath', 'neats', 'necks', 'neddy', 'needs', 'needy', 'neems', 'neeps', 'negus', 'neifs', 'neigh', 'neist', 'nelly', 'nemas', 'nenes', 'neons', 'nerds',
      'nerdy', 'nerol', 'nerts', 'nertz', 'nerve', 'nervy', 'nests', 'nesty', 'netop', 'netts', 'netty', 'neuks', 'neume', 'neums', 'never', 'neves', 'nevus',
      'newel', 'newer', 'newie', 'newly', 'newsy', 'newts', 'nexus', 'ngwee', 'nicad', 'nicer', 'niche', 'nicks', 'nicol', 'nidal', 'nided', 'nides', 'nidus',
      'niece', 'nieve', 'nifty', 'nighs', 'night', 'nihil', 'nills', 'nimbi', 'nines', 'ninja', 'ninny', 'ninon', 'ninth', 'nipas', 'nippy', 'nisei', 'nisus',
      'niter', 'nites', 'nitid', 'niton', 'nitre', 'nitro', 'nitty', 'nival', 'nixed', 'nixes', 'nixie', 'nizam', 'nobby', 'noble', 'nobly', 'nocks', 'nodal',
      'noddy', 'nodes', 'nodus', 'noels', 'noggs', 'nohow', 'noils', 'noily', 'noirs', 'noise', 'noisy', 'nolos', 'nomad', 'nomas', 'nomen', 'nomes', 'nomoi',
      'nomos', 'nonas', 'nonce', 'nones', 'nonet', 'nonyl', 'nooks', 'nooky', 'noons', 'noose', 'nopal', 'noria', 'noris', 'norms', 'north', 'nosed', 'noses',
      'nosey', 'notal', 'notch', 'noted', 'noter', 'notes', 'notum', 'nouns', 'novae', 'novas', 'novel', 'noway', 'nowts', 'nubby', 'nubia', 'nucha', 'nuder',
      'nudes', 'nudge', 'nudie', 'nudzh', 'nuked', 'nukes', 'nulls', 'numbs', 'numen', 'nurds', 'nurls', 'nurse', 'nutsy', 'nutty', 'nyala', 'nylon', 'nymph',
      'oaken', 'oakum', 'oared', 'oases', 'oasis', 'oasts', 'oaten', 'oater', 'oaths', 'oaves', 'obeah', 'obeli', 'obese', 'obeys', 'obias', 'obits', 'objet',
      'oboes', 'obole', 'oboli', 'obols', 'occur', 'ocean', 'ocher', 'ochre', 'ochry', 'ocker', 'ocrea', 'octad', 'octal', 'octan', 'octet', 'octyl', 'oculi',
      'odahs', 'odder', 'oddly', 'odeon', 'odeum', 'odist', 'odium', 'odors', 'odour', 'odyle', 'odyls', 'ofays', 'offal', 'offed', 'offer', 'often', 'ofter',
      'ogams', 'ogees', 'ogham', 'ogive', 'ogled', 'ogler', 'ogles', 'ogres', 'ohias', 'ohing', 'ohmic', 'oidia', 'oiled', 'oiler', 'oinks', 'okapi', 'okays',
      'okehs', 'okras', 'olden', 'older', 'oldie', 'oleic', 'olein', 'oleos', 'oleum', 'olios', 'olive', 'ollas', 'ology', 'omasa', 'omber', 'ombre', 'omega',
      'omens', 'omers', 'omits', 'oncet', 'onery', 'onion', 'onium', 'onlay', 'onset', 'ontic', 'oohed', 'oomph', 'oorie', 'ootid', 'oozed', 'oozes', 'opahs',
      'opals', 'opens', 'opera', 'opine', 'oping', 'opium', 'opsin', 'opted', 'optic', 'orach', 'orals', 'orang', 'orate', 'orbed', 'orbit', 'orcas', 'orcin',
      'order', 'ordos', 'oread', 'organ', 'orgic', 'oribi', 'oriel', 'orles', 'orlon', 'orlop', 'ormer', 'ornis', 'orpin', 'orris', 'ortho', 'orzos', 'osier',
      'osmic', 'osmol', 'ossia', 'ostia', 'other', 'ottar', 'otter', 'ottos', 'ought', 'ounce', 'ouphe', 'ouphs', 'ourie', 'ousel', 'ousts', 'outby', 'outdo',
      'outed', 'outer', 'outgo', 'outre', 'ouzel', 'ouzos', 'ovals', 'ovary', 'ovate', 'ovens', 'overs', 'overt', 'ovine', 'ovoid', 'ovoli', 'ovolo', 'ovule',
      'owing', 'owlet', 'owned', 'owner', 'owsen', 'oxbow', 'oxeye', 'oxide', 'oxids', 'oxime', 'oxims', 'oxlip', 'oxter', 'oyers', 'ozone', 'pacas', 'paced',
      'pacer', 'paces', 'pacey', 'pacha', 'packs', 'pacts', 'paddy', 'padis', 'padle', 'padre', 'padri', 'paean', 'paeon', 'pagan', 'paged', 'pager', 'pages',
      'pagod', 'paiks', 'pails', 'pains', 'paint', 'pairs', 'paisa', 'paise', 'palea', 'paled', 'paler', 'pales', 'palet', 'palls', 'pally', 'palms', 'palmy',
      'palpi', 'palps', 'palsy', 'pampa', 'panda', 'pandy', 'paned', 'panel', 'panes', 'panga', 'pangs', 'panic', 'panne', 'pansy', 'panto', 'pants', 'panty',
      'papal', 'papas', 'papaw', 'paper', 'pappi', 'pappy', 'parae', 'paras', 'parch', 'pardi', 'pards', 'pardy', 'pared', 'pareo', 'parer', 'pares', 'pareu',
      'parge', 'pargo', 'paris', 'parka', 'parks', 'parle', 'parol', 'parrs', 'parry', 'parse', 'parts', 'party', 'parve', 'parvo', 'paseo', 'pases', 'pasha',
      'passe', 'pasta', 'paste', 'pasts', 'pasty', 'patch', 'pated', 'paten', 'pater', 'pates', 'paths', 'patin', 'patio', 'patly', 'patsy', 'patty', 'pause',
      'pavan', 'paved', 'paver', 'paves', 'pavid', 'pavin', 'pavis', 'pawed', 'pawer', 'pawky', 'pawls', 'pawns', 'paxes', 'payed', 'payee', 'payer', 'payor',
      'peace', 'peach', 'peage', 'peags', 'peaks', 'peaky', 'peals', 'peans', 'pearl', 'pears', 'peart', 'pease', 'peats', 'peaty', 'peavy', 'pecan', 'pechs',
      'pecks', 'pecky', 'pedal', 'pedes', 'pedro', 'peeks', 'peels', 'peens', 'peeps', 'peers', 'peery', 'peeve', 'peins', 'peise', 'pekan', 'pekes', 'pekin',
      'pekoe', 'peles', 'pelfs', 'pelon', 'pelts', 'penal', 'pence', 'pends', 'penes', 'pengo', 'penna', 'penne', 'penni', 'penny', 'peons', 'peony', 'pepla',
      'pepos', 'peppy', 'perch', 'perdu', 'perdy', 'perea', 'peres', 'peril', 'peris', 'perks', 'perky', 'perms', 'perps', 'perry', 'perse', 'pervs', 'pesky',
      'pesos', 'pesto', 'pests', 'pesty', 'petal', 'peter', 'petit', 'petti', 'petto', 'petty', 'pewee', 'pewit', 'phage', 'phase', 'phial', 'phlox', 'phone',
      'phono', 'phons', 'phony', 'photo', 'phots', 'phpht', 'phuts', 'phyla', 'phyle', 'piano', 'pians', 'pibal', 'pical', 'picas', 'picks', 'picky', 'picot',
      'picul', 'piece', 'piers', 'pieta', 'piety', 'piggy', 'pigmy', 'piing', 'pikas', 'piked', 'piker', 'pikes', 'pikis', 'pilaf', 'pilar', 'pilau', 'pilaw',
      'pilea', 'piled', 'pilei']

##d = int(input('How many words? '))
##for i in range(d):
##    dd = input('Enter word: ')
##    c3.append(dd)
##print(c3)

for i in range(len(c)):
    a = tuple(c[i])
    bb.append(a)
for i in range(len(c1)):
    a = tuple(c1[i])
    bb1.append(a)
for i in range(len(c2)):
    a = tuple(c2[i])
    bb2.append(a)
for i in range(len(c3)):
    a = tuple(c3[i])
    bb3.append(a)
##
##print(bb)
##print()
##print(bb1)
##print()
##print(bb2)
##print()
##print(bb3)

for i in range(2,len(b)+1):
    print()
    print(i, 'letter words')
    print()
    words = permutations(b,i)
    for i in words:
        if i in bb:
            print(i)
        if i in bb1:
            print(i)
        if i in bb2:
            print(i)
        if i in bb3:
            print(i)

